### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte

### ISSUE THREAD

**Issue by zcgg2zhmm** [conda-forge/miniforge#208]
conda version:  4.10.3

environment：
     OS:     Debian9.13, 64bit 
     uname -a:  Linux linaro-alip 4.4.19415 #1 SMP Tue Aug 17 09:24:19 CST 2021 aarch64 GNU/Linux
     CPU:   RK3399

conda create or pip install, throw exception!
help me please, thanks!!
```
Traceback (most recent call last):
  File "/root/miniforge3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1141, in handle_unexpected_exception
    self._execute_upload(error_report)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1303, in _execute_upload
    'User-Agent': self.user_agent,
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1101, in user_agent
    return context.user_agent
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 775, in user_agent
    builder.append("%s/%s" % self.os_distribution_name_version)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 817, in os_distribution_name_version
    from conda._vendor.distro import id, version
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1084, in <module>
    _distro = LinuxDistribution()
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 601, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
    distro_info = self._parse_distro_release_file(filepath)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
    return self._parse_distro_release_content(fp.readline())
  File "/root/miniforge3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte
     ```

**Comment by isuruf** [comment]
Can you please open this in https://github.com/conda/conda ?

**Comment by zcgg2zhmm** [comment]
> Can you please open this in https://github.com/conda/conda ?

yeah, but....i am looking for my answer..

**Comment by hmaarrfk** [comment]
I think we will have to close this issue on the miniforge. Hopefully you found your answer on the conda installation
