### ISSUE TITLE
tensorflow.yml error in Miniforge while installing dependencies

### ISSUE THREAD

**Issue by eccemerrin** [conda-forge/miniforge#244]
- [ ] Hi. I am an M1 chip user and ı am trying to install tensorflow on my machine. I have watched a lot of videos and follow this [notebook](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb)
- [ ] In the Install Jupyter and Create Environment part, I need to run this command **conda env create -f tensorflow-apple-metal.yml -n tf **. However it produces the mentioned error. How can I solve this. Thanks.
- [ ] I have two environment: 
(base) ecem@Ecem-MacBook-Pro desktop % conda env list
conda environments are at 
                              /Users/ecem/anaconda3
base                     */Users/ecem/miniforge3

<br/>
Environment (<code>conda list</code>):

```
$ conda list
(base) ecem@Ecem-MacBook-Pro desktop % conda list
# packages in environment at /Users/ecem/miniforge3:
#
# Name                    Version                   Build  Channel
anyio                     3.4.0            py39h2804cbe_0    conda-forge
aom                       3.2.0                hc470f4d_2    conda-forge
appnope                   0.1.2            py39h2804cbe_2    conda-forge
argon2-cffi               21.1.0           py39h5161555_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h3422bc3_6    conda-forge
brotli-bin                1.0.9                h3422bc3_6    conda-forge
brotlipy                  0.7.0           py39h5161555_1003    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
cairo                     1.16.0            he69dfd1_1008    conda-forge
certifi                   2021.10.8        py39h2804cbe_1    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0           py39h2804cbe_0    conda-forge
conda-package-handling    1.7.3            py39h5161555_1    conda-forge
cryptography              36.0.1           py39hfb8cd70_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1            py39hfb83b0d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
ffmpeg                    4.4.1                hdbd4ad8_0    conda-forge
fontconfig                2.13.1            heb65262_1005    conda-forge
fonttools                 4.28.5           py39h5161555_0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.6.13               h706517b_1    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
harfbuzz                  2.9.1                h13b3495_1    conda-forge
hdf5                      1.10.6          nompi_h0fc092c_1114    conda-forge
icu                       68.2                 hbdafb3b_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.10.0           py39h2804cbe_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.6.0            py39h32adebf_0    conda-forge
ipython                   7.30.1           py39h2804cbe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
jasper                    2.0.33               hba35424_0    conda-forge
jbig                      2.1               h3422bc3_2003    conda-forge
jedi                      0.18.1           py39h2804cbe_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.3.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39h2804cbe_7    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.9.1            py39h2804cbe_1    conda-forge
jupyter_highlight_selected_word 0.2.0           py39h2804cbe_1005    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py39h2804cbe_2    conda-forge
jupyter_server            1.13.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.9.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.2            py39h4d2d688_1    conda-forge
krb5                      1.19.2               hd92b7a7_3    conda-forge
lame                      3.100             h27ca646_1001    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      3.0                  hbdafb3b_0    conda-forge
libblas                   3.9.0           12_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h3422bc3_6    conda-forge
libbrotlidec              1.0.9                h3422bc3_6    conda-forge
libbrotlienc              1.0.9                h3422bc3_6    conda-forge
libcblas                  3.9.0           12_osxarm64_openblas    conda-forge
libcurl                   7.80.0               h8fe1914_1    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libdeflate                1.8                  h3422bc3_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libglib                   2.70.2               h67e64d8_0    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
liblapack                 3.9.0           12_osxarm64_openblas    conda-forge
liblapacke                3.9.0           12_osxarm64_openblas    conda-forge
libnghttp2                1.43.0               he4cd7f6_1    conda-forge
libopenblas               0.3.18          openmp_h5dd58f0_0    conda-forge
libopencv                 4.5.1            py39h9e916e0_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libprotobuf               3.15.8               hccf11d3_1    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libssh2                   1.10.0               hb80f160_2    conda-forge
libtiff                   4.3.0                h74060c4_2    conda-forge
libvpx                    1.11.0               hc470f4d_3    conda-forge
libwebp                   1.2.1                h0d20362_0    conda-forge
libwebp-base              1.2.1                h3422bc3_0    conda-forge
libxml2                   2.9.12               h538f51a_0    conda-forge
libxslt                   1.1.33               hd2240da_2    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
llvm-openmp               12.0.1               hf3c4609_1    conda-forge
lxml                      4.7.1            py39h3757d6e_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
markupsafe                2.0.1            py39h5161555_1    conda-forge
matplotlib                3.5.0            py39hca03da5_0  
matplotlib-base           3.5.0            py39h5aa4fe7_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h5161555_1005    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nb_conda_kernels          2.3.1            py39h2804cbe_1    conda-forge
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py39h2804cbe_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
nettle                    3.6                  hc6a1b29_0    conda-forge
notebook                  6.4.6              pyha770c72_0    conda-forge
numpy                     1.21.5           py39h47fb9ce_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv                    4.5.1            py39hdf13c20_1    conda-forge
openh264                  2.1.1                habe5f53_0    conda-forge
openssl                   1.1.1l               h3422bc3_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 hbdafb3b_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.1            py39hf1d1977_0  
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
prompt_toolkit            3.0.24               hd8ed1ab_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-opencv                 4.5.1            py39hfa6204d_1    conda-forge
pycosat                   0.6.3           py39h5161555_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.0           py39h5161555_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_4    conda-forge
python                    3.9.7           h54d631c_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h5161555_3    conda-forge
pyzmq                     22.3.0           py39h02c6a76_1    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py39h5161555_1006    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.0.3           py39h2804cbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py39h2804cbe_2    conda-forge
sqlite                    3.37.0               h72a2b83_0    conda-forge
svt-av1                   0.8.7                hc470f4d_1    conda-forge
terminado                 0.12.1           py39h2804cbe_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               he1e0b03_1    conda-forge
tornado                   6.1              py39h5161555_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.2            py39h2804cbe_1    conda-forge
x264                      1!161.3030           h3422bc3_1    conda-forge
x265                      3.5                  h666519e_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            hee7b306_1013    conda-forge
zstd                      1.5.0                h861e0a7_0    conda-forge

```
</details>

(base) ecem@Ecem-MacBook-Pro desktop % conda env create -f tensorflow-apple-metal.yml  -n tf
After this line it raises this error:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 106, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 210, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 141, in check_event
        self.current_event = self.state()
      File "/Users/ecem/miniforge3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 715, in parse_flow_mapping_key
        raise ParserError(
    ruamel_yaml.parser.ParserError: while parsing a flow mapping
      in "<unicode string>", line 1, column 1:
        {\rtf1\ansi\ansicpg1254\cocoartf2580
        ^ (line: 1)
    expected ',' or '}', but got '{'
      in "<unicode string>", line 2, column 34:
        \cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .App ... 
                                         ^ (line: 2)

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/ecem/miniforge3/bin/conda
             CONDA_PREFIX=/Users/ecem/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/ecem/miniforge3/bin/python
               CONDA_ROOT=/Users/ecem/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/ecem/miniforge3/bin:/Users/ecem/miniforge3/bin:/Users/ecem/mini
                          forge3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/ecem/miniforge3
            shell level : 1
       user config file : /Users/ecem/.condarc
 populated config files : /Users/ecem/miniforge3/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __osx=11.6=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/ecem/miniforge3  (writable)
      conda av data dir : /Users/ecem/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/ecem/miniforge3/pkgs
                          /Users/ecem/.conda/pkgs
       envs directories : /Users/ecem/miniforge3/envs
                          /Users/ecem/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Darwin/20.6.0 OSX/11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by hmaarrfk** [comment]
it is rather difficult for us to parse a notebook. we have to read through it all to find the exact file.

can you please provide the file, along with the explicit commands you used?

**Comment by hmaarrfk** [comment]
Closing since this seems to be a support issue with other's instructions, not related to this repo. Please open in the appropriate feedstock.
