### ISSUE TITLE
Error when running `conda activate` in fish shell

### ISSUE THREAD

**Issue by codemonkey800** [conda-forge/miniforge#248]
Issue: Running `conda activate <env>` throws an error when using it in fish shell.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/jasuncion/miniforge3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py39h5161555_1003    conda-forge
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
certifi                   2021.10.8        py39h2804cbe_1    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0           py39h2804cbe_0    conda-forge
conda-package-handling    1.7.3            py39h5161555_1    conda-forge
cryptography              36.0.0           py39hfb8cd70_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
openssl                   1.1.1l               h3422bc3_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39h5161555_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_4    conda-forge
python                    3.9.7           h54d631c_3_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py39h5161555_1006    conda-forge
setuptools                59.4.0           py39h2804cbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h72a2b83_0    conda-forge
tk                        8.6.11               he1e0b03_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zlib                      1.2.11            hee7b306_1013    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /Users/jasuncion/miniforge3
            shell level : 1
       user config file : /Users/jasuncion/.condarc
 populated config files : /Users/jasuncion/miniforge3/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __osx=12.0.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/jasuncion/miniforge3  (writable)
      conda av data dir : /Users/jasuncion/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jasuncion/miniforge3/pkgs
                          /Users/jasuncion/.conda/pkgs
       envs directories : /Users/jasuncion/miniforge3/envs
                          /Users/jasuncion/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Darwin/21.1.0 OSX/12.0.1
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```
</details>

Error when running `conda activate`:
<details>

```
$ conda activate <env>
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 140, in main
        return activator_main()
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/activate.py", line 1210, in main
        print(activator.execute(), end='')
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/activate.py", line 178, in execute
        return getattr(self, self.command)()
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/activate.py", line 152, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/activate.py", line 300, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/activate.py", line 377, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "/Users/jasuncion/miniforge3/lib/python3.9/site-packages/conda/activate.py", line 630, in _replace_prefix_in_path
        if path_list[last_idx + 1] == library_bin_dir:
    IndexError: list index out of range

`$ /Users/jasuncion/miniforge3/bin/conda shell.fish activate napari-org`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=/Users/jasuncion/miniforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/jasuncion/miniforge3/bin/python
               CONDA_ROOT=/Users/jasuncion/miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/jasuncion/miniforge3/bin:/Users/jasuncion/miniforge3/condabin:/
                          opt/homebrew/bin:/Users/jasuncion/projects/misc/dotfiles/bin:node_modu
                          les/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jasuncion
                          /.local/share/nvm/v16.13.0/bin:/Users/jasuncion:/Users/jasuncion/minif
                          orge3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    fish_color_valid_path=--underline

     active environment : base
    active env location : /Users/jasuncion/miniforge3
            shell level : 1
       user config file : /Users/jasuncion/.condarc
 populated config files : /Users/jasuncion/miniforge3/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __osx=12.0.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/jasuncion/miniforge3  (writable)
      conda av data dir : /Users/jasuncion/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jasuncion/miniforge3/pkgs
                          /Users/jasuncion/.conda/pkgs
       envs directories : /Users/jasuncion/miniforge3/envs
                          /Users/jasuncion/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Darwin/21.1.0 OSX/12.0.1
                UID:GID : 503:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```
</details>

**Comment by hmaarrfk** [comment]
Do other conda installers work with fish?  If not, please post an issue to upstream conda.

**Comment by hmaarrfk** [comment]
did you use `conda init fish` or is it teying to sourxe the bash rc file?

**Comment by hmaarrfk** [comment]
Closing as no response from OP. Assumed fixed.
