### ISSUE TITLE
Intermittent crashes, probably network related

### ISSUE THREAD

**Issue by znmeb** [conda-forge/miniforge#295]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For the past few days I've been getting intermittent crashes on `mamba install` operations. There are a lot of moving parts; I'm running in Docker with the NVIDIA container runtime on Windows Subsystem for Linux on Windows 11. I haven't tried any other environments. Note that I am using `mamba`, not `conda`, for all of my installs and other environment management functions. 

The symptom is a display like this:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/synth/mambaforge/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/synth/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 951, in exception_converter
        raise e
      File "/home/synth/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 945, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/synth/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 901, in _wrapped_main
        result = do_call(args, p)
      File "/home/synth/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 763, in do_call
        exit_code = install(args, parser, "install")
      File "/home/synth/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 599, in install
        transaction.fetch_extract_packages()
    RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/linux-64/fftw-3.3.10-nompi_h77c792f_102.tar.bz2]
    Connection timeout after 9064 ms

`$ /home/synth/mambaforge/bin/mamba install --quiet --yes cmake fftw pkg-config`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/home/synth/mambaforge/envs/r-reticulate:/home/synth/mambaforge/envs/r
                          -reticulate/x86_64-conda-linux-gnu/sysroot/usr
      CONDA_BUILD_SYSROOT=/home/synth/mambaforge/envs/r-reticulate/x86_64-conda-linux-
                          gnu/sysroot
        CONDA_DEFAULT_ENV=r-reticulate
                CONDA_EXE=/home/synth/mambaforge/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/home/synth/mambaforge/envs/r-reticulate
    CONDA_PROMPT_MODIFIER=(r-reticulate)
         CONDA_PYTHON_EXE=/home/synth/mambaforge/bin/python
               CONDA_ROOT=/home/synth/mambaforge
              CONDA_SHLVL=1
    CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
     CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
                CUDA_PATH=/home/synth/mambaforge/envs/r-reticulate
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
                     PATH=/home/synth/mambaforge/bin:/home/synth/mambaforge/envs/r-reticulate/bi
                          n:/home/synth/mambaforge/condabin:/usr/local/nvidia/bin:/usr/local/cud
                          a/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : r-reticulate
    active env location : /home/synth/mambaforge/envs/r-reticulate
            shell level : 1
       user config file : /home/synth/.condarc
 populated config files : /home/synth/mambaforge/.condarc
                          /home/synth/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.10.102.1=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/synth/mambaforge  (writable)
      conda av data dir : /home/synth/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/synth/mambaforge/pkgs
                          /home/synth/.conda/pkgs
       envs directories : /home/synth/mambaforge/envs
                          /home/synth/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/5.10.102.1-microsoft-standard-WSL2 ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

This usually goes away on a rerun, but sometimes it takes a couple of tries. 

I tried adjusting the timeouts with `conda config` but that doesn't seem to help. A 9064 ms timeout for a network operation from anywhere in the world to wherever your servers are seems a bit optimistic though. 

At this point I don't have any tools to rule out an NVIDIA, Docker or WSL networking issue. I'd be happy if I knew which timeout was getting triggered and how to increase it to a more practical value.

### Installed packages

```shell
# packages in environment at /home/synth/mambaforge/envs/r-reticulate:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb9d737c_2    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_9    conda-forge
blas                      2.108                       mkl    conda-forge
blas-devel                3.9.0                     8_mkl    conda-forge
bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
boost                     1.77.0           py39h5472131_0    conda-forge
boost-cpp                 1.77.0               h359cf19_1    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            ha12eb4b_1010    conda-forge
certifi                   2021.10.8        py39hf3d152e_2    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cudatoolkit               11.5.1               hcf5317a_9    nvidia
cupy                      10.3.1           py39hc3c280e_0    conda-forge
curl                      7.82.0               h2283fc2_0    conda-forge
cusignal                  22.04.00        py39_g06f58b4_0    rapidsai
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
debugpy                   1.6.0            py39h5a03fae_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
fastrlock                 0.8              py39h5a03fae_2    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.32.0           py39hb9d737c_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc_impl_linux-64         10.3.0              hf2f2afa_15    conda-forge
gcc_linux-64              10.3.0               hc39de41_9    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gfortran_impl_linux-64    10.3.0              h73f4979_15    conda-forge
gfortran_linux-64         10.3.0               hb09a455_9    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.20.1               hcf0ee16_1    conda-forge
gstreamer                 1.20.1               hd4edc92_1    conda-forge
gxx_impl_linux-64         10.3.0              hf2f2afa_15    conda-forge
gxx_linux-64              10.3.0               h2593f52_9    conda-forge
harfbuzz                  4.2.0                h40b6f09_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
importlib-metadata        4.11.3           py39hf3d152e_1    conda-forge
importlib_resources       5.7.1              pyhd8ed1ab_0    conda-forge
ipykernel                 6.13.0           py39hef51801_0    conda-forge
ipython                   8.2.0            py39hf3d152e_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py39hf3d152e_1    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.2.2              pyhd8ed1ab_1    conda-forge
jupyter_core              4.9.2            py39hf3d152e_0    conda-forge
jupyterlab                2.1.0                      py_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         1.0.9                      py_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.2            py39hf939315_1    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libcurl                   7.82.0               h2283fc2_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h28343ad_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     10.3.0              he6cfe16_15    conda-forge
libgcc-ng                 11.2.0              h1d223b6_15    conda-forge
libgfortran-ng            11.2.0              h69a702a_15    conda-forge
libgfortran5              11.2.0              h5c6108e_15    conda-forge
libgit2                   1.4.3                h4c07d5c_0    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   11.2.0              h1d223b6_15    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
liblapacke                3.9.0                     8_mkl    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.2                 h676c864_0    conda-forge
libsanitizer              10.3.0              h26c7422_15    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-devel_linux-64  10.3.0              he6cfe16_15    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_15    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
llvm-openmp               13.0.1               he0ac6c6_1    conda-forge
llvmlite                  0.36.0           py39h1bbdace_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
matplotlib                3.5.1            py39hf3d152e_0    conda-forge
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h3811e60_1005    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-devel                 2020.4             ha770c72_305    conda-forge
mkl-include               2020.4             h726a3e6_304    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.28               h26416b9_4    conda-forge
mysql-libs                8.0.28               hbc51c84_4    conda-forge
nbclient                  0.6.0              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.10             pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.77                 h2350873_0    conda-forge
numba                     0.53.1           py39h56b8d98_1    conda-forge
numpy                     1.22.3           py39h18676bf_2    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.2                h166bdaf_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.18                 ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.50.7               hbd2fdc8_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.0            py39hae2aec6_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
psutil                    5.9.0            py39hb9d737c_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge
pyrsistent                0.18.1           py39hb9d737c_1    conda-forge
python                    3.9.12          h2660328_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.11.0          py3.9_cuda11.5_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyzmq                     22.3.0           py39headdf64_2    conda-forge
qt                        5.12.9               h1304e3e_6    conda-forge
r-askpass                 1.1               r41hcfec24a_2    conda-forge
r-assertthat              0.2.1             r41hc72bb7e_2    conda-forge
r-backports               1.4.1             r41hcfec24a_0    conda-forge
r-base                    4.1.3                hd930d0e_0    conda-forge
r-base64enc               0.1_3           r41hcfec24a_1004    conda-forge
r-brew                    1.0_7             r41hc72bb7e_0    conda-forge
r-brio                    1.1.3             r41hcfec24a_0    conda-forge
r-bslib                   0.3.1             r41hc72bb7e_0    conda-forge
r-cachem                  1.0.6             r41hcfec24a_0    conda-forge
r-callr                   3.7.0             r41hc72bb7e_0    conda-forge
r-cli                     3.2.0             r41h03ef668_0    conda-forge
r-clipr                   0.8.0             r41hc72bb7e_0    conda-forge
r-commonmark              1.8.0             r41h06615bd_0    conda-forge
r-covr                    3.5.1             r41h03ef668_0    conda-forge
r-cpp11                   0.4.2             r41hc72bb7e_0    conda-forge
r-crayon                  1.5.1             r41hc72bb7e_0    conda-forge
r-credentials             1.3.2             r41hc72bb7e_0    conda-forge
r-crosstalk               1.2.0             r41hc72bb7e_0    conda-forge
r-curl                    4.3.2             r41hcfec24a_0    conda-forge
r-data.table              1.14.2            r41hcfec24a_0    conda-forge
r-desc                    1.4.1             r41hc72bb7e_0    conda-forge
r-devtools                2.4.3             r41hc72bb7e_0    conda-forge
r-diffobj                 0.3.5             r41hcfec24a_0    conda-forge
r-digest                  0.6.29            r41h03ef668_0    conda-forge
r-dt                      0.22              r41hc72bb7e_0    conda-forge
r-ellipsis                0.3.2             r41hcfec24a_0    conda-forge
r-evaluate                0.15              r41hc72bb7e_0    conda-forge
r-fansi                   1.0.3             r41h06615bd_0    conda-forge
r-fastmap                 1.1.0             r41h03ef668_0    conda-forge
r-fs                      1.5.2             r41h7525677_1    conda-forge
r-gert                    1.5.0             r41h30f61c7_1    conda-forge
r-gh                      1.3.0             r41hc72bb7e_0    conda-forge
r-git2r                   0.30.1            r41hf72769b_0    conda-forge
r-gitcreds                0.1.1             r41hc72bb7e_0    conda-forge
r-glue                    1.6.2             r41h06615bd_0    conda-forge
r-here                    1.0.1             r41hc72bb7e_0    conda-forge
r-highr                   0.9               r41hc72bb7e_0    conda-forge
r-htmltools               0.5.2             r41h03ef668_0    conda-forge
r-htmlwidgets             1.5.4             r41hc72bb7e_0    conda-forge
r-httr                    1.4.2             r41hc72bb7e_0    conda-forge
r-ini                     0.3.1           r41hc72bb7e_1003    conda-forge
r-irdisplay               1.1               r41hd8ed1ab_0    conda-forge
r-irkernel                1.3               r41hc72bb7e_0    conda-forge
r-jquerylib               0.1.4             r41hc72bb7e_0    conda-forge
r-jsonlite                1.8.0             r41h06615bd_0    conda-forge
r-knitr                   1.38              r41hc72bb7e_0    conda-forge
r-later                   1.2.0             r41h03ef668_0    conda-forge
r-lattice                 0.20_45           r41hcfec24a_0    conda-forge
r-lazyeval                0.2.2             r41hcfec24a_2    conda-forge
r-lifecycle               1.0.1             r41hc72bb7e_0    conda-forge
r-magrittr                2.0.3             r41h06615bd_0    conda-forge
r-matrix                  1.4_1             r41h0154571_0    conda-forge
r-memoise                 2.0.1             r41hc72bb7e_0    conda-forge
r-mime                    0.12              r41hcfec24a_0    conda-forge
r-openssl                 2.0.0             r41h1f3e0c5_0    conda-forge
r-pbdzmq                  0.3_7             r41h42bf92c_0    conda-forge
r-pillar                  1.7.0             r41hc72bb7e_0    conda-forge
r-pkgbuild                1.3.1             r41hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r41hc72bb7e_1    conda-forge
r-pkgload                 1.2.4             r41h03ef668_0    conda-forge
r-png                     0.1_7           r41hcfec24a_1004    conda-forge
r-praise                  1.0.0           r41hc72bb7e_1005    conda-forge
r-prettyunits             1.1.1             r41hc72bb7e_1    conda-forge
r-processx                3.5.3             r41h06615bd_0    conda-forge
r-promises                1.2.0.1           r41h03ef668_0    conda-forge
r-ps                      1.6.0             r41hcfec24a_0    conda-forge
r-purrr                   0.3.4             r41hcfec24a_1    conda-forge
r-r6                      2.5.1             r41hc72bb7e_0    conda-forge
r-rappdirs                0.3.3             r41hcfec24a_0    conda-forge
r-rcmdcheck               1.4.0             r41h785f33e_0    conda-forge
r-rcpp                    1.0.8.3           r41h7525677_0    conda-forge
r-rcpptoml                0.1.7             r41h03ef668_1    conda-forge
r-rematch2                2.1.2             r41hc72bb7e_1    conda-forge
r-remotes                 2.4.2             r41hc72bb7e_0    conda-forge
r-renv                    0.15.4            r41hc72bb7e_0    conda-forge
r-repr                    1.1.4             r41h785f33e_0    conda-forge
r-reticulate              1.24              r41h03ef668_0    conda-forge
r-rex                     1.2.1             r41hc72bb7e_0    conda-forge
r-rlang                   1.0.2             r41h7525677_0    conda-forge
r-rmarkdown               2.13              r41hc72bb7e_1    conda-forge
r-roxygen2                7.1.2             r41h03ef668_0    conda-forge
r-rprojroot               2.0.3             r41hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r41hc72bb7e_0    conda-forge
r-rversions               2.1.1             r41hc72bb7e_0    conda-forge
r-sass                    0.4.1             r41h7525677_0    conda-forge
r-sessioninfo             1.2.2             r41hc72bb7e_0    conda-forge
r-stringi                 1.7.6             r41h337692f_1    conda-forge
r-stringr                 1.4.0             r41hc72bb7e_2    conda-forge
r-sys                     3.4               r41hcfec24a_0    conda-forge
r-testthat                3.1.3             r41h7525677_0    conda-forge
r-tibble                  3.1.6             r41hcfec24a_0    conda-forge
r-tinytex                 0.38              r41hc72bb7e_0    conda-forge
r-usethis                 2.1.5             r41hc72bb7e_0    conda-forge
r-utf8                    1.2.2             r41hcfec24a_0    conda-forge
r-uuid                    1.0_4             r41h06615bd_0    conda-forge
r-vctrs                   0.4.1             r41h7525677_0    conda-forge
r-waldo                   0.4.0             r41hc72bb7e_0    conda-forge
r-whisker                 0.4               r41hc72bb7e_1    conda-forge
r-withr                   2.5.0             r41hc72bb7e_0    conda-forge
r-xfun                    0.30              r41h7525677_0    conda-forge
r-xml2                    1.3.3             r41h03ef668_0    conda-forge
r-xopen                   1.0.0           r41hc72bb7e_1003    conda-forge
r-yaml                    2.3.5             r41h06615bd_0    conda-forge
r-zip                     2.2.0             r41hcfec24a_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.8.0            py39hee8e79c_1    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                62.1.0           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               h4ff8645_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
terminado                 0.13.3           py39hf3d152e_1    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
torchaudio                0.11.0               py39_cu115    pytorch
tornado                   6.1              py39hb9d737c_3    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing_extensions         4.2.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39hb9d737c_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

### Environment info

```shell
$ conda info

     active environment : r-reticulate
    active env location : /home/synth/mambaforge/envs/r-reticulate
            shell level : 1
       user config file : /home/synth/.condarc
 populated config files : /home/synth/mambaforge/.condarc
                          /home/synth/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.10.102.1=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/synth/mambaforge  (writable)
      conda av data dir : /home/synth/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/synth/mambaforge/pkgs
                          /home/synth/.conda/pkgs
       envs directories : /home/synth/mambaforge/envs
                          /home/synth/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/5.10.102.1-microsoft-standard-WSL2 ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by znmeb** [comment]
I'm going to close this - I managed to get the connection timeout to work at 60 seconds. This is probably a WSL issue; I'm having network problems in "straight" WSL, without either Docker or Mambaforge in the loop. If this comes up for other people, see this issue:

https://github.com/microsoft/WSL/issues/6416#issuecomment-1107636406

**Comment by znmeb** [comment]
@florin-ciornei I opened a Windows 11 feedback issue for this. It appears to be something in WSL. I can reproduce it installing R packages from source.
