### ISSUE TITLE
AttributeError: module 'importlib.util' has no attribute 'abc'

### ISSUE THREAD

**Issue by McLawrence** [conda-forge/miniforge#344]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I just upgraded from 4.12 to 4.14. Running `conda` gives this error. Uninstalling and reinstalling does not fix the issue. Reverting back to `4.12.0.0` works. 

I am on MacOS M1 Pro, so the arm64 build.

```
Traceback (most recent call last):
  File "/Users/lhemmen/miniforge3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/lhemmen/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 118, in main
    from ..exceptions import conda_exception_handler
  File "/Users/lhemmen/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 19, in <module>
    from .models.channel import Channel
  File "/Users/lhemmen/miniforge3/lib/python3.10/site-packages/conda/models/channel.py", line 13, in <module>
    from ..base.context import context, Context
  File "/Users/lhemmen/miniforge3/lib/python3.10/site-packages/conda/base/context.py", line 51, in <module>
    from ..common.configuration import (Configuration, ConfigurationLoadError, MapParameter,
  File "/Users/lhemmen/miniforge3/lib/python3.10/site-packages/conda/common/configuration.py", line 32, in <module>
    from .path import expand
  File "/Users/lhemmen/miniforge3/lib/python3.10/site-packages/conda/common/path.py", line 17, in <module>
    from distutils.spawn import find_executable
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/Users/lhemmen/.local/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 72, in find_spec
    return self.get_distutils_spec()
  File "/Users/lhemmen/.local/lib/python3.10/site-packages/_distutils_hack/__init__.py", line 77, in get_distutils_spec
    class DistutilsLoader(importlib.util.abc.Loader):
AttributeError: module 'importlib.util' has no attribute 'abc'

```

### Installed packages

```shell
conda does not run.
```

### Environment info

```shell
conda does not run.
```

**Comment by hmaarrfk** [comment]
Sooooo. Thank you for posting the detailed traceback.

I don't have a mac, but something that looks suspect is `/Users/lhemmen/.local/lib/python3.10/site-packages`. 

Python has some strange resolution rules. My suspicion is that somebody asked you to use the command
```
pip install --user  PACKAGE_NAME
```
which installs the package in your specific user's namespace. I'm not sure of the history of the `--user` flag, but I think it has fallen out of fashion and virtual environment (or conda environment) have taken its place. The reason is that `--user` is shared between all virtual environments, and thus can render things incompatible (especially if conda-forge's installer expect a different version of a specific package)

If I were you, I would ~~delete~~ move the directory `/Users/lhemmen/.local/lib/python3.10` and try again:

```
mv /Users/lhemmen/.local/lib/python3.10 /Users/lhemmen/DOT_LOCAL_LIB_PYTHON310_BACKUP
```

and try again.

**Comment by McLawrence** [comment]
Thanks! I just worked with the older version for a while, but just ran into the problem again on another project. Your suspicion was correct and your proposed solution worked! 👍
