### ISSUE TITLE
BUG: ARM mambaforge breaks when updating mamba in x86 environment

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/miniforge#346]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I used the ARM mambaforge to install mamba on my apple silicon M1.

My base environment is hence in arm.

But to use nextstrain, I have an x86 environment, configured more or less as follows:

```
conda create -n nextstrain python
conda activate nextstrain
conda config --env --set subdir osx-64
```

I can't quite remember what exactly I did, but my thinking is that I updated `mamba` from the x86 directory, maybe through `update --all`.

In any case, I now can no longer run `mamba`. So I can't even export packages to reinstall `mambaforge` and get back to my latest state.

I've described the issue originally in the mamba repo but was told that they couldn't do much.

Maybe this is more of a miniforge issue than a mamba issue: https://github.com/mamba-org/mamba/issues/1897#issue-1360106036

In any case, does anyone know what I can do to rescue myself?

Maybe fat binaries of the mamba libraries would make it possible to use mamba in both x86 emulation and arm environments?

### Installed packages

```shell
Can't run conda list:


❯ mamba update --all              
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: dlopen(/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libsolv.1.dylib'
  Referenced from: '/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so'
  Reason: tried: '/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/../../../libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/../../../libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Caskroom/mambaforge/base/bin/../lib/libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Caskroom/mambaforge/base/bin/../lib/libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libsolv.1.dylib' (no such file), '/usr/lib/libsolv.1.dylib' (no such file)
```
```


### Environment info

```shell
Can't run conda list
```

**Comment by isuruf** [comment]
You can do a separate installation of mambaforge using
```
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash Mambaforge-$(uname)-$(uname -m).sh
```
and then use that conda/mamba to repair the old installation by doing
`conda install libffi libsolv --force-reinstall -p /opt/homebrew/Caskroom/mambaforge/base/`

**Comment by corneliusroemer** [comment]
Thanks @isuruf - that's helpful but it doesn't seem to work.

Something is confused about architectures and I have no clue to fix.

After doing a separate installation of mambaforge, I had to first figure out how to deactivate the base environment:
```
./mambaforge/bin/conda config --set auto_activate_base false 
conda deactivate
```

Otherwise the broken environment would still be active:
```

Looking for: ['libffi', 'libsolv']

pkgs/main/osx-64                                     4.5MB @   3.2MB/s  1.5s
bioconda/noarch                                      3.7MB @   2.4MB/s  1.7s
bioconda/osx-64                                      3.5MB @   2.1MB/s  1.8s
pkgs/r/noarch                                        1.3MB @ 715.4kB/s  0.4s
pkgs/main/noarch                                   816.0kB @ 396.0kB/s  0.5s
pkgs/r/osx-64                                      820.9kB @ 392.9kB/s  0.4s
conda-forge/noarch                                   9.3MB @   3.2MB/s  3.2s
conda-forge/osx-64                                  23.1MB @   2.7MB/s  9.3s
error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.
error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.

Pinned packages:
  - python 3.10.*
```

It doesn't want to work so I'm installing miniforge now, hoping that `conda` remains as a fallback in case `mamba` breaks again.

Something's very broken about architecture resolution.
