### ISSUE TITLE
New miniforge install asks for `conda=22.11.0` to be installed, then conflicts with base install packages

### ISSUE THREAD

**Issue by derekschinke** [conda-forge/miniforge#389]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

After installing miniforge and running `conda update --all`, it says:

```
==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.0
```

After installing it with required dependency `python=3.11` (`conda install conda=22.11.0 python=3.11`), it installs mostly fine, until the very end when it spits this out:

```
Retrieving notices: ...working... failed
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1129, in __call__
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main.py", line 86, in main_subshell
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/core.py", line 75, in wrapper
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/core.py", line 39, in display_notices
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/http.py", line 36, in get_notice_responses
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/http.py", line 39, in <genexpr>
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/concurrent/futures/_base.py", line 458, in result
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/http.py", line 42, in <lambda>
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/cache.py", line 37, in wrapper
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/requests/adapters.py", line 460, in send
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/requests/adapters.py", line 263, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/certifi/cacert.pem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main.py", line 129, in main
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1429, in conda_exception_handler
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1172, in handle_exception
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1183, in handle_unexpected_exception
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1245, in print_unexpected_error_report
ModuleNotFoundError: No module named 'conda.cli.main_info'
```

However, the installation appear to finish, and `python --version` returns `Python 3.11.0`. However, attempting `conda update --all` again returns the following conflicts:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package wheel conflicts for:
python=3.11 -> pip -> wheel
pip -> wheel

Package pip conflicts for:
python=3.11 -> pip
conda[version='>=22.11.0'] -> python[version='>=3.11,<3.12.0a0'] -> pip

Package python_abi conflicts for:
conda[version='>=22.11.0'] -> python_abi=3.11[build=*_cp311]
conda[version='>=22.11.0'] -> conda-package-handling[version='>=1.3.0'] -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp310|*_cp39']

Package certifi conflicts for:
conda[version='>=22.11.0'] -> requests[version='>=2.20.1,<3'] -> certifi[version='>=2016.9.26|>=2017.4.17']
pip -> setuptools -> certifi[version='>=2016.9.26']
```

### Installed packages

```shell
brotlipy                  0.7.0           py311he2be06e_1005    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.9.24            h4653dfc_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311hae827db_2    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.11.0         py311h267d04e_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              38.0.4          py311h507f6e9_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
openssl                   3.0.7                h03a7124_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pycosat                   0.6.4           py311he2be06e_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.0          h93c2e33_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.17.21         py311he2be06e_2    conda-forge
ruamel.yaml.clib          0.2.7           py311he2be06e_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zstandard                 0.19.0          py311hdcbfb07_1    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /opt/homebrew/Caskroom/miniforge/base
            shell level : 1
       user config file : /Users/derekschinke/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
          conda version : 22.11.0
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __archspec=arm64=0
                          __osx=13.0.1=0
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/derekschinke/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/derekschinke/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.0 requests/2.28.1 CPython/3.11.0 Darwin/22.1.0 OSX/13.0.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by dholth** [comment]
How does `python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp310|*_cp39']` get decided?

**Comment by hmaarrfk** [comment]
The TLS error is suspicious

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/admin-requests/pull/523

It seems the package might have been pulled.

**Comment by derekschinke** [comment]
Downgraded back to 22.9.0, and the Warning for upgrading to 22.11.0 has disappeared for now.
