### ISSUE TITLE
Conda, miniforge3 on MacOS fails to run after updating conda.

### ISSUE THREAD

**Issue by emilfh** [conda-forge/miniforge#464]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

After updating Conda on Latest MacOS, with either conda update --all, conda update conda or conda update -n base -c conda-forge conda, Conda does not work. 

When installing latest OS X | arm64 (Apple Silicon) installer from here I can get Conda back to working, but running update again and same problem. Conda does not work in base or any other environment. 

### I am getting the following output:

"         
emil@Emils-MacBookAir ~ % conda
KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
    return func(*args, **kwargs)
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 57, in main_subshell
    p = generate_parser()
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 69, in generate_parser
    configure_parser_create(sub_parsers)
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 650, in configure_parser_create
    add_parser_solver(solver_mode_options)
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 1816, in add_parser_solver
    solver.name for solver in context.plugin_manager.get_hook_results("solvers")
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 78, in get_hook_results
    (item for items in hook() for item in items),
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 1244, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/main_info.py", line 236, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])

KeyError: 'pkgs_dirs'

   Traceback (most recent call last):
      File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 69, in generate_parser
        configure_parser_create(sub_parsers)
      File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 650, in configure_parser_create
        add_parser_solver(solver_mode_options)
      File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 1816, in add_parser_solver
        solver.name for solver in context.plugin_manager.get_hook_results("solvers")
      File "/Users/emil/miniforge3/lib/python3.10/site-packages/conda/plugins/manager.py", line 78, in get_hook_results
        (item for items in hook() for item in items),
    TypeError: 'NoneType' object is not iterable

$ /Users/emil/miniforge3/bin/conda

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.
"

### And the following output when running conda init after install:

"
by running conda init? [yes|no]
[no] >>> yes
no change     /Users/emil/miniforge3/condabin/conda
no change     /Users/emil/miniforge3/bin/conda
no change     /Users/emil/miniforge3/bin/conda-env
no change     /Users/emil/miniforge3/bin/activate
no change     /Users/emil/miniforge3/bin/deactivate
modified      /Users/emil/miniforge3/etc/profile.d/conda.sh
modified      /Users/emil/miniforge3/etc/fish/conf.d/conda.fish
no change     /Users/emil/miniforge3/shell/condabin/Conda.psm1
no change     /Users/emil/miniforge3/shell/condabin/conda-hook.ps1
no change     /Users/emil/miniforge3/lib/python3.10/site-packages/xontrib/conda.xsh
modified      /Users/emil/miniforge3/etc/profile.d/conda.csh
no change     /Users/emil/.zshrc
"

### Installed packages

```shell
% conda list
# packages in environment at /Users/emil/miniforge3:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
brotlipy                  0.7.0           py310h8e9501a_1005    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1          py310h2399d43_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.5.0                   pypi_0    pypi
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.8.0                    pypi_0    pypi
cryptography              41.0.1                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.1.2                   pypi_0    pypi
pluggy                    1.1.0                    pypi_0    pypi
pycosat                   0.6.4           py310h8e9501a_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1                   pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.10         h3ba56d0_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.28.2                   pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel.yaml               0.17.32         py310h2aa6e3c_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h8e9501a_1    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15                  pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.9                h1a8c8d9_0    conda-forge
zstandard                 0.19.0          py310had9512b_1    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
```

### Environment info

```shell
% conda info

     active environment : None
            shell level : 0
       user config file : /Users/emil/.condarc
 populated config files : /Users/emil/miniforge3/.condarc
                          /Users/emil/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/emil/miniforge3  (writable)
      conda av data dir : /Users/emil/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/emil/miniforge3/pkgs
                          /Users/emil/.conda/pkgs
       envs directories : /Users/emil/miniforge3/envs
                          /Users/emil/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Darwin/22.5.0 OSX/13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by cenkt** [comment]
Same here on Windows11...

**Comment by xtronaltic** [comment]
Same here

**Comment by jaimergp** [comment]
This is a bug with `pluggy 1.1.0`, now retired. You can `pip install pluggy=1.0.0 --no-deps` to downgrade as a fix.

**Comment by cenkt** [comment]
I think it is brotli-1.0.9 that still causes the problem. So  pip install brotlipy==0.7.0 --no-deps solved my problem on Windows 11.

**Comment by emilfh** [comment]
> This is a bug with `pluggy 1.1.0`, now retired. You can `pip install pluggy=1.0.0 --no-deps` to downgrade as a fix.

Thanks, running ` pip3 install pluggy=1.0.0 --no-deps` inside base environment, to downgrade seems to have resolved the problem for me. Now Conda runs without problem.
