### ISSUE TITLE
Uninstall Bug

### ISSUE THREAD

**Issue by ktehranchi** [conda-forge/miniforge#503]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I ran into some python versioning issues, which I couldn't figure out how to solve, so I decided to uninstall miniforge so that I can start clean. After completing step one on the uninstall instructions `conda init --reverse`, I got this error:

```
conda init --reverse

Could not load conda plugin `conda-libmamba-solver`:

dlopen(/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /usr/local/Caskroom/miniforge/base/lib/libmamba.2.0.0.dylib
  Reason: tried: '/usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)
Password:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/cli/main_init.py", line 33, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/core/initialize.py", line 113, in initialize
        run_plan_elevated(plan2)
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/core/initialize.py", line 709, in run_plan_elevated
        result = subprocess_call(
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/conda/gateways/subprocess.py", line 98, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/local/Caskroom/miniforge/base/lib/python3.10/subprocess.py", line 2001, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /usr/local/Caskroom/miniforge/base/bin/conda init --reverse`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/usr/local/Caskroom/miniforge/base/bin/conda
             CONDA_PREFIX=/usr/local/Caskroom/miniforge/base
           CONDA_PREFIX_1=/Users/kamrantehranchi/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/usr/local/Caskroom/miniforge/base/bin/python
               CONDA_ROOT=/usr/local/Caskroom/miniforge/base
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/local/Caskroom/miniforge/base/bin:/Users/kamrantehranchi/opt/mini
                          conda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/loca
                          l/opt:/Applications/VMware
                          Fusion.app/Contents/Public:/Library/TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /usr/local/Caskroom/miniforge/base
            shell level : 2
       user config file : /Users/kamrantehranchi/.condarc
 populated config files : /usr/local/Caskroom/miniforge/base/.condarc
                          /Users/kamrantehranchi/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=12.1=0
                          __unix=0=0
       base environment : /usr/local/Caskroom/miniforge/base  (writable)
      conda av data dir : /usr/local/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/Caskroom/miniforge/base/pkgs
                          /Users/kamrantehranchi/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniforge/base/envs
                          /Users/kamrantehranchi/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/21.2.0 OSX/12.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

Now, any time I use the mamba command i get this error:
```
mamba init
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: dlopen(/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /usr/local/Caskroom/miniforge/base/lib/libmamba.2.0.0.dylib
  Reason: tried: '/usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)
```

### Installed packages

```shell
onda list
Could not load conda plugin `conda-libmamba-solver`:

dlopen(/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /usr/local/Caskroom/miniforge/base/lib/libmamba.2.0.0.dylib
  Reason: tried: '/usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)
# packages in environment at /usr/local/Caskroom/miniforge/base:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0          py310hecd8cb5_0
brotlipy                  0.7.0           py310hca72f7f_1002
bzip2                     1.0.8                h1de35cc_0
c-ares                    1.19.1               h6c40b1e_0
ca-certificates           2023.08.22           hecd8cb5_0
certifi                   2023.7.22       py310hecd8cb5_0
cffi                      1.15.1          py310h6c40b1e_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
conda                     23.3.1          py310h2ec42d9_0    conda-forge
conda-libmamba-solver     23.3.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0           py310hecd8cb5_0
conda-package-streaming   0.9.0           py310hecd8cb5_0
cryptography              41.0.3          py310h30e54ef_0
fmt                       9.1.0                ha357a0b_0
icu                       73.1                 hcec6c5f_0
idna                      3.4             py310hecd8cb5_0
jsonpatch                 1.32               pyhd3eb1b0_0
jsonpointer               2.1                pyhd3eb1b0_0
krb5                      1.20.1               h428f121_1
libarchive                3.6.2                h29ab7a1_2
libcurl                   8.4.0                hf20ceda_0
libcxx                    14.0.6               h9765a3e_0
libedit                   3.1.20221030         h6c40b1e_0
libev                     4.33                 h9ed2024_1
libffi                    3.4.4                hecd8cb5_0
libiconv                  1.16                 hca72f7f_2
libmamba                  1.4.2                h9d281b0_0    conda-forge
libmambapy                1.4.2           py310hb15139c_0    conda-forge
libnghttp2                1.57.0               h9beae6a_0
libsolv                   0.7.24               hfff2838_0
libsqlite                 3.43.2               h92b6c6a_0    conda-forge
libssh2                   1.10.0               h04015c4_2
libxml2                   2.10.4               h1bd7e62_1
libzlib                   1.2.13               h8a1eda9_5    conda-forge
lz4-c                     1.9.4                hcec6c5f_0
mamba                     1.4.2           py310h6bde348_0    conda-forge
ncurses                   6.4                  hcec6c5f_0
openssl                   3.1.3                h8a1eda9_0    conda-forge
packaging                 23.1            py310hecd8cb5_0
pcre2                     10.42                h9b97e30_0
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310hecd8cb5_1
pybind11-abi              4                    hd3eb1b0_1
pycosat                   0.6.6           py310h6c40b1e_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 23.2.0          py310hecd8cb5_0
pysocks                   1.7.1           py310hecd8cb5_0
python                    3.10.12         had23ca6_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
readline                  8.2                  hca72f7f_0
reproc                    14.2.4               he9d5cce_1
reproc-cpp                14.2.4               he9d5cce_1
requests                  2.31.0          py310hecd8cb5_0
ruamel.yaml               0.17.21         py310hca72f7f_0
ruamel.yaml.clib          0.2.7           py310h6729b98_2    conda-forge
setuptools                68.0.0          py310hecd8cb5_0
tk                        8.6.12               h5d9f67b_0
toolz                     0.12.0          py310hecd8cb5_0
tqdm                      4.65.0          py310h20db666_0
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.16         py310hecd8cb5_0
wheel                     0.41.2          py310hecd8cb5_0
xz                        5.4.2                h6c40b1e_0
yaml-cpp                  0.7.0                he9d5cce_1
zlib                      1.2.13               h8a1eda9_5    conda-forge
zstandard                 0.19.0          py310h6c40b1e_0
zstd                      1.5.5                hc035e20_0
```

### Environment info

```shell
conda info
Could not load conda plugin `conda-libmamba-solver`:

dlopen(/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /usr/local/Caskroom/miniforge/base/lib/libmamba.2.0.0.dylib
  Reason: tried: '/usr/local/Caskroom/miniforge/base/lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/lib/python3.10/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/Caskroom/miniforge/base/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)

     active environment : base
    active env location : /usr/local/Caskroom/miniforge/base
            shell level : 2
       user config file : /Users/kamrantehranchi/.condarc
 populated config files : /usr/local/Caskroom/miniforge/base/.condarc
                          /Users/kamrantehranchi/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=12.1=0
                          __unix=0=0
       base environment : /usr/local/Caskroom/miniforge/base  (writable)
      conda av data dir : /usr/local/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/Caskroom/miniforge/base/pkgs
                          /Users/kamrantehranchi/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniforge/base/envs
                          /Users/kamrantehranchi/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/21.2.0 OSX/12.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by ktehranchi** [comment]
I figured it out.... just ran all uninstall instructions with sudo in front of first step. Fully uninstalled and then reinstalled.
