### ISSUE TITLE
mamba clean broken on Windows mamba v1.5.4 / conda 23.11

### ISSUE THREAD

**Issue by ahrib** [conda-forge/miniforge#534]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

To repeat:
- Clean install of Mamba on a virtual machine using the windows x64 mambaforge installer (not miniforge)
- perform `mamba update mamba conda`  this upgrades mamba 1.5.4 and conda 23.11
- perform `mamba update --all` 
- perform `mamba clean --all`

result:
```
(base) C:\Users\windows>mamba clean --all
No module named 'conda.cliconda'

\# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\windows\mambaforge\lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "C:\Users\windows\mambaforge\lib\site-packages\mamba\mamba.py", line 956, in exception_converter
        raise e
      File "C:\Users\windows\mambaforge\lib\site-packages\mamba\mamba.py", line 949, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Users\windows\mambaforge\lib\site-packages\mamba\mamba.py", line 895, in _wrapped_main
        result = do_call(parsed_args, p)
      File "C:\Users\windows\mambaforge\lib\site-packages\mamba\mamba.py", line 758, in do_call
        exit_code = clean(args, parser)
      File "C:\Users\windows\mambaforge\lib\site-packages\mamba\mamba.py", line 701, in clean
        module = import_module("conda.cli" + relative_mod, __name__.rsplit(".", 1)[0])
      File "C:\Users\windows\mambaforge\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'conda.cliconda'

`$ C:\Users\windows\mambaforge\Scripts\mamba clean --all`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\windows\mambaforge\condabin\..\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\windows\mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\windows\mambaforge\python.exe
               CONDA_ROOT=C:\Users\windows\mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\windows
               LD_PRELOAD=<not set>
                     PATH=C:\Users\windows\mambaforge;C:\Users\windows\mambaforge\Library\mingw-
                          w64\bin;C:\Users\windows\mambaforge\Library\usr\bin;C:\Users\windows\m
                          ambaforge\Library\bin;C:\Users\windows\mambaforge\Scripts;C:\Users\win
                          dows\mambaforge\bin;C:\Users\windows\mambaforge\condabin;C:\Windows\sy
                          stem32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windows
                          PowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Users\windows\AppData\L
                          ocal\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\windows\mambaforge
            shell level : 1
       user config file : C:\Users\windows\.condarc
 populated config files : C:\Users\windows\mambaforge\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\Users\windows\mambaforge  (writable)
      conda av data dir : C:\Users\windows\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\windows\mambaforge\pkgs
                          C:\Users\windows\.conda\pkgs
                          C:\Users\windows\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\windows\mambaforge\envs
                          C:\Users\windows\.conda\envs
                          C:\Users\windows\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.4
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

workaround:
- downgrade to mamba 1.5.3 and conda 23.10 by performing `mamba install conda=23.10`

### Installed packages

```shell
(base) C:\Users\windows>conda list
# packages in environment at C:\Users\windows\mambaforge:
#
# Name                    Version                   Build  Channel
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310h00ffb61_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2023.11.17           h56e8100_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h8d17308_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.11.0         py310h5588dad_1    conda-forge
conda-libmamba-solver     23.11.1            pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.7          py310hb1f9477_1    conda-forge
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
fmt                       10.1.1               h181d51b_1    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py310h5588dad_3    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
libarchive                3.7.2                h6f8411a_0    conda-forge
libcurl                   8.4.0                hd5e4a3a_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libmamba                  1.5.4                h3f09ed1_0    conda-forge
libmambapy                1.5.4           py310h04f2035_0    conda-forge
libsolv                   0.7.27               h12be248_0    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libxml2                   2.11.6               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
mamba                     1.5.4           py310hd9d798f_0    conda-forge
menuinst                  2.0.0           py310h00ffb61_1    conda-forge
miniforge_console_shortcut 2.0                  h57928b3_1    conda-forge
openssl                   3.2.0                hcfcfb64_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py310h8d17308_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.3.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.13         h4de0772_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
reproc                    14.2.4.post0         hcfcfb64_1    conda-forge
reproc-cpp                14.2.4.post0         h63175ca_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.5          py310h8d17308_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h8d17308_2    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml-cpp                  0.8.0                h63175ca_0    conda-forge
zstandard                 0.22.0          py310h0009e47_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### Environment info

```shell
(base) C:\Users\windows>conda info

     active environment : base
    active env location : C:\Users\windows\mambaforge
            shell level : 1
       user config file : C:\Users\windows\.condarc
 populated config files : C:\Users\windows\mambaforge\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\Users\windows\mambaforge  (writable)
      conda av data dir : C:\Users\windows\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\windows\mambaforge\pkgs
                          C:\Users\windows\.conda\pkgs
                          C:\Users\windows\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\windows\mambaforge\envs
                          C:\Users\windows\.conda\envs
                          C:\Users\windows\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.4
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
Sound like upstream issue ( https://github.com/mamba-org/mamba/issues/3033 )

Let's consolidate discussion in that issue

There have been no installer releases so a fresh installer should still provide Conda & Mamba versions from before the problem arose

Also note that there are several people hard at work on this issue
