### ISSUE TITLE
can't start the terminal vscode (macbook m2 pro)

### ISSUE THREAD

**Issue by deven367** [conda-forge/miniforge#541]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Miniforge was working alright, until all of a sudden the shell crashed. I can't use any of my environments. All I get is this error.
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/cli/main.py", line 94, in main_sourced
        print(activator.execute(), end="")
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/activate.py", line 171, in execute
        return getattr(self, self.command)()
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/activate.py", line 143, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/activate.py", line 304, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/activate.py", line 385, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
      File "/Users/deven367/miniforge3/lib/python3.10/site-packages/conda/activate.py", line 696, in _get_deactivate_scripts
        entry.path for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
      File "/Users/deven367/miniforge3/lib/python3.10/posixpath.py", line 76, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /Users/deven367/miniforge3/bin/conda shell.posix activate base`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/deven367/miniforge3/bin/conda
           CONDA_PREFIX_2=/Users/deven367/miniforge3/envs/torch
           CONDA_PREFIX_3=/Users/deven367/miniforge3
         CONDA_PYTHON_EXE=/Users/deven367/miniforge3/bin/python
               CONDA_ROOT=/Users/deven367/miniforge3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/X11/s
                          hare/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/opt/home
                          brew/share/man::
                     PATH=/Users/deven367/.modular/pkg/packages.modular.com_mojo/bin:/Library/Fr
                          ameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/hom
                          ebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:
                          /usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/boot
                          strap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/
                          bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bo
                          otstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Lib
                          rary/TeX/texbin:/Applications/quarto/bin:/Users/deven367/.cargo/bin:/U
                          sers/deven367/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 4
       user config file : /Users/deven367/.condarc
 populated config files : /Users/deven367/miniforge3/.condarc
                          /Users/deven367/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=14.2=0
                          __unix=0=0
       base environment : /Users/deven367/miniforge3  (writable)
      conda av data dir : /Users/deven367/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/deven367/miniforge3/pkgs
                          /Users/deven367/.conda/pkgs
       envs directories : /Users/deven367/miniforge3/envs
                          /Users/deven367/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/23.2.0 OSX/14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### Installed packages

```shell
# packages in environment at /Users/deven367/miniforge3:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310h1253130_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2399d43_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.3.1          py310hbe9552e_0    conda-forge
conda-libmamba-solver     23.3.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.3          py310hdd3b5e7_0    conda-forge
fmt                       9.1.0                hffc8910_0    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
libarchive                3.6.2                h82b9b87_1    conda-forge
libcurl                   8.2.1                hc52a3a8_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libmamba                  1.4.2                h7d1d596_0    conda-forge
libmambapy                1.4.2           py310h34b6e76_0    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libsolv                   0.7.24               ha614eb4_3    conda-forge
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libxml2                   2.11.5               h25269f3_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
mamba                     1.4.2           py310ha5d4528_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.2                h53f4e23_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h8e9501a_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         h01493a6_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
reproc                    14.2.4               h1a8c8d9_0    conda-forge
reproc-cpp                14.2.4               hb7217d7_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.32         py310h2aa6e3c_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h8e9501a_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml-cpp                  0.7.0                hb7217d7_2    conda-forge
zstandard                 0.19.0          py310h8e9501a_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /Users/deven367/miniforge3
            shell level : 5
       user config file : /Users/deven367/.condarc
 populated config files : /Users/deven367/miniforge3/.condarc
                          /Users/deven367/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=14.2=0
                          __unix=0=0
       base environment : /Users/deven367/miniforge3  (writable)
      conda av data dir : /Users/deven367/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/deven367/miniforge3/pkgs
                          /Users/deven367/.conda/pkgs
       envs directories : /Users/deven367/miniforge3/envs
                          /Users/deven367/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/23.2.0 OSX/14.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jaimergp** [comment]
Can you try with `source /Users/deven367/miniforge3/etc/profile.d/conda.sh` and then `conda activate`?

**Comment by deven367** [comment]
@jaimergp The terminal somehow started to work after a reboot. However, #539 still remains unresolved. 
<img width="894" alt="image" src="https://github.com/conda-forge/miniforge/assets/31466137/be9ba05c-65ad-4dad-a4f0-3d4f0d82ec2a">
