### ISSUE TITLE
No module named 'rpds.rpds'

### ISSUE THREAD

**Issue by GrigoriiTarasov** [conda-forge/miniforge#556]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Can't run installed jupyter lab on todays clean miniforge-pypy3 installation

jupyter lab
```
Traceback (most recent call last):
  File "C:\ProgramData\miniforge-pypy3\Scripts\jupyter-lab-script.py", line 6, in <module>
    from jupyterlab.labapp import main
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jupyterlab\__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jupyterlab\handlers\announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jupyter_server\base\handlers.py", line 24, in <module>
    from jupyter_events import EventLogger
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jupyter_events\__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jupyter_events\logger.py", line 14, in <module>
    from jsonschema import ValidationError
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jsonschema\__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jsonschema\_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\jsonschema\exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\referencing\__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\referencing\_core.py", line 8, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
  File "C:\ProgramData\miniforge-pypy3\lib\site-packages\rpds\__init__.py", line 1, in <module>
    from .rpds import *
ModuleNotFoundError: No module named 'rpds.rpds'

```

### Installed packages

```shell
anyio                     4.2.0            py39haa95532_0
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-lru                 2.0.4            py39haa95532_0
attrs                     23.1.0           py39haa95532_0
babel                     2.11.0           py39haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.12.2           py39haa95532_0
bleach                    4.1.0              pyhd3eb1b0_0
boltons                   23.1.1             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0            py39h3665ca7_1    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2023.12.12           haa95532_0
certifi                   2024.2.2         py39haa95532_0
cffi                      1.16.0           py39h7a188e9_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.2            py39haa95532_0
conda                     23.11.0          py39h0d475fb_1    conda-forge
conda-libmamba-solver     23.12.0            pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.7            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
distro                    1.8.0              pyhd8ed1ab_0    conda-forge
entrypoints               0.4              py39haa95532_0
exceptiongroup            1.2.0            py39haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.5.0                h63175ca_1    conda-forge
fmt                       10.1.1               h181d51b_1    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1            py39haa95532_0
ipykernel                 6.28.0           py39haa95532_0
ipython                   8.15.0           py39haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.18.1           py39haa95532_1
jinja2                    3.1.3            py39haa95532_0
json5                     0.9.6              pyhd3eb1b0_0
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4              py39h0d475fb_3    conda-forge
jsonschema                4.19.2           py39haa95532_0
jsonschema-specifications 2023.7.1         py39haa95532_0
jupyter-lsp               2.2.0            py39haa95532_0
jupyter_client            7.4.9            py39haa95532_0
jupyter_core              5.5.0            py39haa95532_0
jupyter_events            0.8.0            py39haa95532_0
jupyter_server            2.10.0           py39haa95532_0
jupyter_server_terminals  0.4.4            py39haa95532_1
jupyterlab                4.0.11           py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.25.1           py39haa95532_0
krb5                      1.21.2               heb0366b_0    conda-forge
libarchive                3.7.2                h313118b_1    conda-forge
libcurl                   8.5.0                hd5e4a3a_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libmamba                  1.5.5                h3f09ed1_0    conda-forge
libmambapy                1.5.5            py39h993ce4e_0    conda-forge
libsodium                 1.0.18               h62dcd97_0
libsolv                   0.7.27               h12be248_0    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libxml2                   2.12.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
mamba                     1.5.5            py39h749ce95_0    conda-forge
markupsafe                2.1.3            py39h2bbff1b_0
matplotlib-inline         0.1.6            py39haa95532_0
menuinst                  2.0.1            py39h3665ca7_0    conda-forge
miniforge_console_shortcut 1.0                  h57928b3_0    conda-forge
mistune                   2.0.4            py39haa95532_0
nb_conda_kernels          2.3.1            py39haa95532_0
nbclassic                 1.0.0            py39haa95532_0
nbclient                  0.8.0            py39haa95532_0
nbconvert                 7.10.0           py39haa95532_0
nbformat                  5.9.2            py39haa95532_0
nest-asyncio              1.6.0            py39haa95532_0
notebook                  6.5.4            py39haa95532_1
notebook-shim             0.2.3            py39haa95532_0
openssl                   3.2.0                hcfcfb64_1    conda-forge
overrides                 7.4.0            py39haa95532_0
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1           py39haa95532_0
prompt-toolkit            3.0.43           py39haa95532_0
psutil                    5.9.0            py39h2bbff1b_0
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0             pyhd3eb1b0_0
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6            py39h7a188e9_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.15.1           py39haa95532_1
pypy3.9                   7.3.13               h994e1e7_1    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.18                0_73_pypy    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39haa95532_0
python-json-logger        2.0.7            py39haa95532_0
python_abi                3.9               4_pypy39_pp73    conda-forge
pytz                      2023.3.post1     py39haa95532_0
pywin32                   305              py39h2bbff1b_0
pywinpty                  2.0.10           py39h5da7b33_0
pyyaml                    6.0.1            py39h2bbff1b_0
pyzmq                     24.0.1           py39hc8fc7ba_1    conda-forge
referencing               0.30.2           py39haa95532_0
reproc                    14.2.4.post0         hcfcfb64_1    conda-forge
reproc-cpp                14.2.4.post0         h63175ca_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4            py39haa95532_0
rfc3986-validator         0.1.1            py39haa95532_0
rpds-py                   0.10.6           py39h062c2fa_0
ruamel.yaml               0.18.5           py39h7a188e9_0    conda-forge
ruamel.yaml.clib          0.2.7            py39h7a188e9_2    conda-forge
send2trash                1.8.2            py39haa95532_0
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0            py39haa95532_0
soupsieve                 2.5              py39haa95532_0
sqlite                    3.44.2               hcfcfb64_0    conda-forge
stack_data                0.2.0              pyhd3eb1b0_0
terminado                 0.17.1           py39haa95532_0
tinycss2                  1.2.1            py39haa95532_0
tk                        8.6.13               h5226925_1    conda-forge
tomli                     2.0.1            py39haa95532_0
tornado                   6.3.3            py39h2bbff1b_0
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.7.1            py39haa95532_0
typing-extensions         4.9.0            py39haa95532_1
typing_extensions         4.9.0            py39haa95532_1
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
websocket-client          0.58.0           py39haa95532_4
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                he774522_0
yaml-cpp                  0.8.0                h63175ca_0    conda-forge
zeromq                    4.3.4                hd77b12b_0
zipp                      3.17.0           py39haa95532_0
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstandard                 0.22.0           py39hdf01746_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

### Environment info

```shell
active environment : None
       user config file : C:\Users\Lenovo\.condarc
 populated config files : C:\ProgramData\miniforge-pypy3\.condarc
                          C:\Users\Lenovo\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.9.18.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\ProgramData\miniforge-pypy3  (writable)
      conda av data dir : C:\ProgramData\miniforge-pypy3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\ProgramData\miniforge-pypy3\pkgs
                          C:\Users\Lenovo\.conda\pkgs
                          C:\Users\Lenovo\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\miniforge-pypy3\envs
                          C:\Users\Lenovo\.conda\envs
                          C:\Users\Lenovo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 PyPy/3.9.18 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by GrigoriiTarasov** [comment]
Fixed by installing jsonschema==4.17.3
