### ISSUE TITLE
Error During Final Deconvolution with Clustering Enabled for E. coli tRNA Analysis in MimSeq

### ISSUE THREAD

**Issue by AteeshaNegi** [conda-forge/miniforge#621]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am trying to analyze the abundance, modification, and charging in tRNA of E. coli and mito tRNA of Human samples. When I use the following command for a human tRNA sample, the MimSeq code runs without any interruption. The command for MELAS sample:

`
mimseq --species Hsap --threads 16 --control-condition 0_Control -n mimseq_Melas_test --out-dir ./mimseq_MELASE_YN --cluster --cluster-id 0.95 --min-cov 2000 --max-mismatches 0.1 --remap --remap-mismatches 0.075 MELAS_samples.txt `

However, when I use the same command for E. coli, I encounter an error during the final deconvolution step. The command used is:

`mimseq --species Ecol --threads 16 --control-condition EV_Control -n mimseq_A_bc1 --out-dir ./cluster_mimseq_A_bc1_test --cluster --cluster-id 0.95 --min-cov 2000 --max-mismatches 0.1 --remap --remap-mismatches 0.075 AlaGGC_A_bc1_test.txt > ./cluster_mimseq_output.logs`

Error Log:
```
+-----------------------------------+         
| Final deconvolution and filtering |         
+-----------------------------------+
2024-08-03 12:25:48,458 [INFO ] 2 clusters filtered out according to minimum coverage threshold: 1000.0 total read coverage per isodecoder.
2024-08-03 12:25:49,374 [INFO ] Output final tables, counts and new mods...
2024-08-03 12:25:49,682 [INFO ] ** Read counts per anticodon saved to ./clusterID85_mimseq_A_bc1_test/counts/Anticodon_counts_raw.txt **
2024-08-03 12:25:49,682 [INFO ] ** Read counts per isodecoder saved to ./clusterID85_mimseq_A_bc1_test/counts/Isodecoder_counts_raw.txt **
2024-08-03 12:25:49,682 [INFO ] 2 sequences could not be deconvoluted as >10% parent assigned-reads do not match parent sequence!
2024-08-03 12:25:49,682 [INFO ] Reasons for this include misalignment of reads to an incorrect cluster, or inaccurate alignment by GSNAP (e.g. at indels in reads) prohibiting correct deconvolution.
2024-08-03 12:25:49,682 [INFO ] 2 total unique sequences not deconvoluted due to mismatches at modified sites, insufficient coverage or read mismatches to parent
Traceback (most recent call last):
  File "/home/hou_lab/miniforge3/envs/mimseq/bin/mimseq", line 8, in <module>
    sys.exit(main())
  File "/home/hou_lab/miniforge3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 421, in main
    args.misinc_thresh, args.mito, args.plastid, args.pretrnas, args.local_mod, args.p_adj, args.crosstalks, args.sampledata)
  File "/home/hou_lab/miniforge3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 165, in mimseq
    isodecoder_sizes = writeIsodecoderInfo(out, name, isodecoder_sizes,readRef_unsplit_newNames, tRNA_dict)
  File "/home/hou_lab/miniforge3/envs/mimseq/lib/python3.7/site-packages/mimseq/splitClusters.py", line 485, in writeIsodecoderInfo
    iso_min = min([x.split("-")[-1] for x in isodecoder_list])
ValueError: min() arg is an empty sequence
```
When I use the --no-cluster flag, I don't encounter this issue, but the alignment shows a high percentage of multi-mapping reads (Uniquely mapped reads: 48%; Multi-mapping reads: 48%).

With clustering, the uniquely mapped reads increase to 97%, but the run is interrupted and does not produce the final alignment folder, mod folder, or other output folders.

Questions:

1) What might be causing this error during the final deconvolution step with clustering enabled for E. coli?
2) Are there specific flags or parameters I should adjust to resolve this issue?
3) What is the significance of clustering in terms of isodecoders and overall tRNA modification analysis in MimSeq?

Any insights or suggestions to resolve this would be greatly appreciated. Thank you!

### Installed packages

```shell
(mimseq) hou_lab@Hou-lab-Precision:~$ conda list
# packages in environment at /home/hou_lab/miniforge3/envs/mimseq:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
biopython                 1.81                     pypi_0    pypi
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.23.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2023.11.17               pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
curl                      8.5.0                hca28451_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc_impl_linux-64         13.2.0               h338b0a0_3    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    13.2.0               h76e1118_3    conda-forge
gmap                      2019.02.26      pl526h2f06484_0    bioconda
gmp                       6.3.0                h59595ed_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gxx_impl_linux-64         13.2.0               h338b0a0_3    conda-forge
harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                      pypi_0    pypi
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     13.2.0             ha9c7c90_103    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgit2                   1.7.1                h76de150_1    conda-forge
libglib                   2.78.2               h783c2da_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsanitizer              13.2.0               h7e041cc_3    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  13.2.0             ha9c7c90_103    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.6               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
matplotlib                3.5.3                    pypi_0    pypi
mimseq                    1.3.8                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.21.6                   pypi_0    pypi
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandoc                    3.1.3                h32600fe_0    conda-forge
pango                     1.50.14              ha41ecd1_2    conda-forge
patsy                     0.5.4                    pypi_0    pypi
pcre2                     10.42                hcad00b1_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pillow                    9.5.0                    pypi_0    pypi
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h59595ed_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybedtools                0.9.1                    pypi_0    pypi
pyfiglet                  0.8.post1                pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
r                         4.3             r43hd8ed1ab_1007    conda-forge
r-askpass                 1.2.0             r43h57805ef_0    conda-forge
r-assertthat              0.2.1             r43hc72bb7e_4    conda-forge
r-base                    4.3.2                hb8ee39d_1    conda-forge
r-base64enc               0.1_3           r43h57805ef_1006    conda-forge
r-boot                    1.3_28.1          r43hc72bb7e_1    conda-forge
r-brew                    1.0_8             r43hc72bb7e_2    conda-forge
r-brio                    1.1.3             r43h57805ef_2    conda-forge
r-bslib                   0.6.1             r43hc72bb7e_0    conda-forge
r-cachem                  1.0.8             r43h57805ef_1    conda-forge
r-callr                   3.7.3             r43hc72bb7e_1    conda-forge
r-class                   7.3_22            r43h57805ef_1    conda-forge
r-cli                     3.6.1             r43ha503ecb_1    conda-forge
r-clipr                   0.8.0             r43hc72bb7e_2    conda-forge
r-cluster                 2.1.6             r43h61816a4_0    conda-forge
r-codetools               0.2_19            r43hc72bb7e_1    conda-forge
r-commonmark              1.9.0             r43h57805ef_1    conda-forge
r-cpp11                   0.4.7             r43hc72bb7e_0    conda-forge
r-crayon                  1.5.2             r43hc72bb7e_2    conda-forge
r-credentials             2.0.1             r43hc72bb7e_0    conda-forge
r-curl                    5.1.0             r43hf9611b0_0    conda-forge
r-desc                    1.4.2             r43hc72bb7e_2    conda-forge
r-devtools                2.4.5             r43hc72bb7e_2    conda-forge
r-diffobj                 0.3.5             r43h57805ef_2    conda-forge
r-digest                  0.6.33            r43ha503ecb_0    conda-forge
r-downlit                 0.4.3             r43hc72bb7e_0    conda-forge
r-ellipsis                0.3.2             r43h57805ef_2    conda-forge
r-evaluate                0.23              r43hc72bb7e_0    conda-forge
r-fansi                   1.0.5             r43h57805ef_0    conda-forge
r-fastmap                 1.1.1             r43ha503ecb_1    conda-forge
r-fontawesome             0.5.2             r43hc72bb7e_0    conda-forge
r-foreign                 0.8_86            r43h57805ef_0    conda-forge
r-fs                      1.6.3             r43ha503ecb_0    conda-forge
r-gert                    2.0.1             r43hc25a090_0    conda-forge
r-gh                      1.4.0             r43hc72bb7e_1    conda-forge
r-gitcreds                0.1.2             r43hc72bb7e_2    conda-forge
r-glue                    1.6.2             r43h57805ef_2    conda-forge
r-highr                   0.10              r43hc72bb7e_1    conda-forge
r-htmltools               0.5.7             r43ha503ecb_0    conda-forge
r-htmlwidgets             1.6.4             r43hc72bb7e_0    conda-forge
r-httpuv                  1.6.13            r43ha503ecb_0    conda-forge
r-httr                    1.4.7             r43hc72bb7e_0    conda-forge
r-httr2                   1.0.0             r43hc72bb7e_0    conda-forge
r-ini                     0.3.1           r43hc72bb7e_1005    conda-forge
r-jquerylib               0.1.4             r43hc72bb7e_2    conda-forge
r-jsonlite                1.8.8             r43h57805ef_0    conda-forge
r-kernsmooth              2.23_22           r43h13b3f57_0    conda-forge
r-knitr                   1.45              r43hc72bb7e_0    conda-forge
r-later                   1.3.2             r43ha503ecb_0    conda-forge
r-lattice                 0.22_5            r43h57805ef_0    conda-forge
r-lifecycle               1.0.4             r43hc72bb7e_0    conda-forge
r-magrittr                2.0.3             r43h57805ef_2    conda-forge
r-mass                    7.3_60            r43h57805ef_1    conda-forge
r-matrix                  1.6_4             r43h316c678_0    conda-forge
r-memoise                 2.0.1             r43hc72bb7e_2    conda-forge
r-mgcv                    1.9_0             r43h316c678_0    conda-forge
r-mime                    0.12              r43h57805ef_2    conda-forge
r-miniui                  0.1.1.1         r43hc72bb7e_1004    conda-forge
r-nlme                    3.1_164           r43h61816a4_0    conda-forge
r-nnet                    7.3_19            r43h57805ef_1    conda-forge
r-openssl                 2.1.1             r43hb353fa6_0    conda-forge
r-pillar                  1.9.0             r43hc72bb7e_1    conda-forge
r-pkgbuild                1.4.2             r43hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r43hc72bb7e_3    conda-forge
r-pkgdown                 2.0.7             r43hc72bb7e_1    conda-forge
r-pkgload                 1.3.3             r43hc72bb7e_0    conda-forge
r-praise                  1.0.0           r43hc72bb7e_1007    conda-forge
r-prettyunits             1.2.0             r43hc72bb7e_0    conda-forge
r-processx                3.8.2             r43h57805ef_0    conda-forge
r-profvis                 0.3.8             r43h57805ef_3    conda-forge
r-promises                1.2.1             r43ha503ecb_0    conda-forge
r-ps                      1.7.5             r43h57805ef_1    conda-forge
r-purrr                   1.0.2             r43h57805ef_0    conda-forge
r-r6                      2.5.1             r43hc72bb7e_2    conda-forge
r-ragg                    1.2.6             r43h73ae6e3_0    conda-forge
r-rappdirs                0.3.3             r43h57805ef_2    conda-forge
r-rcmdcheck               1.4.0             r43h785f33e_2    conda-forge
r-rcpp                    1.0.11            r43h7df8631_0    conda-forge
r-recommended             4.3             r43hd8ed1ab_1006    conda-forge
r-rematch2                2.1.2             r43hc72bb7e_3    conda-forge
r-remotes                 2.4.2.1           r43hc72bb7e_0    conda-forge
r-rlang                   1.1.2             r43ha503ecb_0    conda-forge
r-rmarkdown               2.25              r43hc72bb7e_0    conda-forge
r-roxygen2                7.2.3             r43ha503ecb_1    conda-forge
r-rpart                   4.1.23            r43h57805ef_0    conda-forge
r-rprojroot               2.0.4             r43hc72bb7e_0    conda-forge
r-rstudioapi              0.15.0            r43hc72bb7e_0    conda-forge
r-rversions               2.1.2             r43hc72bb7e_2    conda-forge
r-sass                    0.4.8             r43ha503ecb_0    conda-forge
r-sessioninfo             1.2.2             r43hc72bb7e_2    conda-forge
r-shiny                   1.8.0             r43h785f33e_0    conda-forge
r-sourcetools             0.1.7_1           r43ha503ecb_1    conda-forge
r-spatial                 7.3_17            r43h57805ef_0    conda-forge
r-stringi                 1.8.2             r43h9facbd6_0    conda-forge
r-stringr                 1.5.1             r43h785f33e_0    conda-forge
r-survival                3.5_7             r43h57805ef_0    conda-forge
r-sys                     3.4.2             r43h57805ef_1    conda-forge
r-systemfonts             1.0.5             r43haf97adc_0    conda-forge
r-testthat                3.2.1             r43ha503ecb_0    conda-forge
r-textshaping             0.3.7             r43hd87b9d6_0    conda-forge
r-tibble                  3.2.1             r43h57805ef_2    conda-forge
r-tinytex                 0.49              r43hc72bb7e_0    conda-forge
r-urlchecker              1.0.1             r43hc72bb7e_2    conda-forge
r-usethis                 2.2.2             r43hc72bb7e_0    conda-forge
r-utf8                    1.2.4             r43h57805ef_0    conda-forge
r-vctrs                   0.6.5             r43ha503ecb_0    conda-forge
r-waldo                   0.5.2             r43hc72bb7e_0    conda-forge
r-whisker                 0.4.1             r43hc72bb7e_1    conda-forge
r-withr                   2.5.2             r43hc72bb7e_0    conda-forge
r-xfun                    0.41              r43ha503ecb_0    conda-forge
r-xml2                    1.3.6             r43h1ad5fc0_0    conda-forge
r-xopen                   1.0.0           r43hc72bb7e_1005    conda-forge
r-xtable                  1.8_4             r43hc72bb7e_5    conda-forge
r-yaml                    2.3.7             r43h57805ef_1    conda-forge
r-zip                     2.3.0             r43h57805ef_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.12.2                   pypi_0    pypi
sed                       4.8                  he412f7d_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.44.2               h2c6b66d_0    conda-forge
statsmodels               0.13.5                   pypi_0    pypi
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tktable                   2.10                 h0c5db8f_5    conda-forge
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

### Environment info

```shell
(mimseq) hou_lab@Hou-lab-Precision:~$ conda info

     active environment : mimseq
    active env location : /home/hou_lab/miniforge3/envs/mimseq
            shell level : 3
       user config file : /home/hou_lab/.condarc
 populated config files : /home/hou_lab/miniforge3/.condarc
                          /home/hou_lab/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/hou_lab/miniforge3  (writable)
      conda av data dir : /home/hou_lab/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /home/hou_lab/miniforge3/pkgs
                          /home/hou_lab/.conda/pkgs
       envs directories : /home/hou_lab/miniforge3/envs
                          /home/hou_lab/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.15.0-113-generic ubuntu/20.04.6 glibc/2.31
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
Conda forge is really only enable in ensuring the packages are installed correctly. 

We aren’t really in a position to help support their usage from a scientific perspective. 

try posting on their official channels
https://github.com/nedialkova-lab/mim-tRNAseq

**Comment by AteeshaNegi** [comment]
Thank you for the suggestion. Appreciated !
