### ISSUE TITLE
CondaHTTPError on new installation of miniforge - WSL2 Debian

### ISSUE THREAD

**Issue by lord-zo** [conda-forge/miniforge#66]
Issue:

Hello,
Despite the title mentioning miniforge, I suspect that the <code>CondaHTTPError</code> I'm running has more to do with packages in the conda-forge distribution.
I wasn't quite sure where I should mention this issue - I've seen similar CondaHTTPErrors on the [conda/conda](https://github.com/conda/conda/issues/10341) repo - but I think this is specific to conda-forge (linux-64?).
If it seems otherwise please let me know - I'm new here.
I have been trying to install the miniforge distribution using the latest <code>Miniforge3-4.9.0-4-Linux-x86_64.sh</code> release yet each time after I run the installer, the command <code>conda update conda</code> raises a <code>CondaHTTPError</code>.
I don't think it's an issue with my network or my computer (running WSL2 Debian) since I have no trouble installing and using a fresh installation of <code>Miniconda3-latest-Linux-x86_64.sh</code> (from [here](https://docs.conda.io/en/latest/miniconda.html#linux-installers)) and updating it to the latest version and installing new packages.
But if I tell miniconda to use the conda-forge channel, I can <code>conda update conda</code> once so that the packages from the conda default channel are replaced by the conda forge channel and then I also get the same <code>CondaHTTPError</code> when I subsequently run <code>conda update conda</code>.

I hope the details below help explain the problem.
I can try and debug further with any additional suggestions.
Thank you in advance for any help

<br/>
Environment (new Miniforge installation) (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/lxvm/miniforge3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
certifi                   2020.11.8        py38h578d9bd_0    conda-forge
cffi                      1.14.3           py38h1bdcb99_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
conda                     4.9.0            py38h924ce5b_1    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
cryptography              3.2.1            py38h7699a38_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tqdm                      4.52.0             pyhd3deb0d_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /home/lxvm/miniforge3
            shell level : 1
       user config file : /home/lxvm/.condarc
 populated config files : /home/lxvm/miniforge3/.condarc
          conda version : 4.9.0
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/lxvm/miniforge3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/lxvm/miniforge3/pkgs
                          /home/lxvm/.conda/pkgs
       envs directories : /home/lxvm/miniforge3/envs
                          /home/lxvm/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.25.0 CPython/3.8.6 Linux/4.4.0-19041-Microsoft debian/10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

Error message <code>conda update conda</code>
The tracebacks call to the conda, requests, and urllib3 packages.

<details>

```
$ conda update conda -v

Collecting package metadata (current_repodata.json): ...working... Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f360586a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /conda-forge/noarch/current_repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36058a30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /conda-forge/linux-64/current_repodata.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36058c40>: Failed to establish a new connection: [Errno -2] Name or service not known')': /conda-forge/noarch/current_repodata.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36058d30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /conda-forge/linux-64/current_repodata.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36058ee0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /conda-forge/noarch/current_repodata.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36058fd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /conda-forge/linux-64/current_repodata.json

failed
Traceback (most recent call last):
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/lxvm/miniforge3/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2f36044880>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36044880>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 499, in fetch_repodata_remote_request
    resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/current_repodata.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f36044880>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/cli/main_update.py", line 20, in execute
    install(args, parser, 'update')
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
    index, r = self._prepare(prepared_specs)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/solve.py", line 1020, in _prepare
    reduced_index = get_reduced_index(self.prefix, self.channels,
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/index.py", line 276, in get_reduced_index
    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 120, in query_all
    result = tuple(concat(executor.map(subdir_query, channel_urls)))
  File "/home/lxvm/miniforge3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/lxvm/miniforge3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/lxvm/miniforge3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/lxvm/miniforge3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 112, in <lambda>
    subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 125, in query
    self.load()
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 189, in load
    _internal_state = self._load()
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 259, in _load
    raw_repodata_str = fetch_repodata_remote_request(
  File "/home/lxvm/miniforge3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 604, in fetch_repodata_remote_request
    raise CondaHTTPError(help_message,
conda.exceptions.CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/linux-64'
```
</details>

**Comment by lord-zo** [comment]
Hi, 

This issue is unresolved on my machine.
It seems that the networking equipment that comes with conda-forge + python doesn't work with my machine.
Should I bring this up in the [conda-forge python feedstock](https://github.com/conda-forge/python-feedstock) instead?

My previous post is still an ongoing issue, though as I mentioned I had a workaround with using miniconda rather than miniforge.

I have been developing my own python package and when I try to install it using pip inside a virtual environment (a bare installation of python 3 from either the default or conda-forge channel) using `pip install <local package dir>` then as pip tries to install setuptools it runs into NewConnectionErrors. An example is here:

<details>

```
$ pip install <package root dir>
Processing <package root dir>
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: ~/miniconda3/envs/test/bin/python ~/miniconda3/envs/test/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-c5_cj16j/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8a4a181f0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8a4a18400>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8a4a185b0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8a4a18760>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe8a4a18910>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
ERROR: Command errored out with exit status 1: ~/miniconda3/envs/test/bin/python ~/miniconda3/envs/test/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-c5_cj16j/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools Check the logs for full command output.
```
</details>

I've been building my project locally with the following minimal initialization scripts:

<details>

```
$ cat pyproject.toml
[build-system]
requires = ["setuptools>=40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

$ cat setup.py
#!/usr/bin/env python3
from setuptools import setup
if __name__ == '__main__':
    setup()

$ cat MANIFEST.ini
include pyproject.toml
```
</details> 

I'm pretty sure this is a conda python recipe problem related to urllib and WSL2 Debian because I do not get any Connection Errors when retrying installing my package using pip and python as installed by Debian's apt.
So I'll probably report this to the conda-forge/python-feedstock as well.

**Comment by lord-zo** [comment]
Closing. Using python venvs ends up working better for me

**Comment by hmaarrfk** [comment]
I'm sorry. It is really difficult for us to test all configurations. Personally. I feel it is better to use native windows builds on windows where you can.

**Comment by lord-zo** [comment]
It's totally fine, don't be sorry. Software projects shouldn't be expected to work on every platform, like religions shouldn't have to work for all people. Believing otherwise would be dogmatic and exhausting, it seems. Clearly, the only dogma here is my choice of WSL. Thank you for helping me recognize the more supported option.
