### ISSUE TITLE
Install in custom directory

### ISSUE THREAD

**Issue by mdtanker** [conda-forge/miniforge#683]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I'm trying to install into a directory that isn't home, since I don't have write permissions in home. I'm using the -p prefix option:
```
bash Miniforge3-Linux-x86_64.sh -p /local/data/muskox/Users/mtankersley/miniforge3
```
but am receiving the following error:

```
mkdir: cannot create directory ‘/home/mtankersley/.conda’: No such file or directory
```
which makes it seem the custom directory set with -p is not working and it's still trying to install in the home directory. 

This seems related to issue #560.

The full output from the install is below:

<details>

<summary>Install outputs</summary>

```
[mtankersley@muskox mtankersley]$ bash Miniforge3-Linux-x86_64.sh -p /local/data/muskox/Users/mtankersley/miniforge3

Welcome to Miniforge3 24.9.2-0

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>> 
Miniforge installer code uses BSD-3-Clause license as stated below.

Binary packages that come with it have their own licensing terms
and by installing miniforge you agree to the licensing terms of individual
packages as well. They include different OSI-approved licenses including
the GNU General Public License and can be found in pkgs/<pkg-name>/info/licenses
folders.

Miniforge installer comes with a bootstrapping executable that is used
when installing miniforge and is deleted after miniforge is installed.
The bootstrapping executable uses micromamba, cli11, cpp-filesystem,
curl, c-ares, krb5, libarchive, libev, lz4, nghttp2, openssl, libsolv,
nlohmann-json, reproc and zstd which are licensed under BSD-3-Clause,
MIT and OpenSSL licenses. Licenses and copyright notices of these
projects can be found at the following URL.
https://github.com/conda-forge/micromamba-feedstock/tree/master/recipe.

=============================================================================

Copyright (c) 2019-2022, conda-forge
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


Do you accept the license terms? [yes|no]
>>> 
Please answer 'yes' or 'no':'
>>> yes

Miniforge3 will now be installed into this location:
/local/data/muskox/Users/mtankersley/miniforge3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/local/data/muskox/Users/mtankersley/miniforge3] >>> 
PREFIX=/local/data/muskox/Users/mtankersley/miniforge3

Transaction

  Prefix: /local/data/muskox/Users/mtankersley/miniforge3/envs/_virtual_specs_checks

  All requested packages already installed

Dry run. Not executing the transaction.
Unpacking payload ...
Extracting _libgcc_mutex-0.1-conda_forge.tar.bz2
Extracting ca-certificates-2024.8.30-hbcca054_0.conda
Extracting ld_impl_linux-64-2.43-h712a8e2_2.conda
Extracting pybind11-abi-4-hd8ed1ab_3.tar.bz2
Extracting python_abi-3.12-5_cp312.conda
Extracting tzdata-2024b-hc8b5060_0.conda
Extracting libgomp-14.2.0-h77fa898_1.conda
Extracting _openmp_mutex-4.5-2_gnu.tar.bz2
Extracting libgcc-14.2.0-h77fa898_1.conda
Extracting libexpat-2.6.4-h5888daf_0.conda
Extracting libgcc-ng-14.2.0-h69a702a_1.conda
Extracting libstdcxx-14.2.0-hc0a3c3a_1.conda
Extracting libzlib-1.3.1-hb9d3cd8_2.conda
Extracting openssl-3.3.2-hb9d3cd8_0.conda
Extracting bzip2-1.0.8-h4bc722e_7.conda
Extracting c-ares-1.32.3-h4bc722e_0.conda
Extracting keyutils-1.6.1-h166bdaf_0.tar.bz2
Extracting libev-4.33-hd590300_2.conda
Extracting libffi-3.4.2-h7f98852_5.tar.bz2
Extracting libiconv-1.17-hd590300_2.conda
Extracting libnsl-2.0.1-hd590300_0.conda
Extracting libsqlite-3.47.0-hadc24fc_1.conda
Extracting libssh2-1.11.0-h0841786_0.conda
Extracting libstdcxx-ng-14.2.0-h4852527_1.conda
Extracting libuuid-2.38.1-h0b41bf4_0.conda
Extracting libxcrypt-4.4.36-hd590300_1.conda
Extracting lzo-2.10-hd590300_1001.conda
Extracting ncurses-6.5-he02047a_1.conda
Extracting reproc-14.2.4.post0-hd590300_1.conda
Extracting tk-8.6.13-noxft_h4845f30_101.conda
Extracting xz-5.2.6-h166bdaf_0.tar.bz2
Extracting fmt-10.2.1-h00ab1b0_0.conda
Extracting libedit-3.1.20191231-he28a2e2_2.tar.bz2
Extracting libnghttp2-1.64.0-h161d5f1_0.conda
Extracting libsolv-0.7.30-h3509ff9_0.conda
Extracting libxml2-2.13.4-h064dc61_2.conda
Extracting lz4-c-1.9.4-hcb278e6_0.conda
Extracting readline-8.2-h8228510_1.conda
Extracting reproc-cpp-14.2.4.post0-h59595ed_1.conda
Extracting yaml-cpp-0.8.0-h59595ed_0.conda
Extracting zstd-1.5.6-ha6fb4c9_0.conda
Extracting krb5-1.21.3-h659f571_0.conda
Extracting libarchive-3.7.4-hfca40fe_0.conda
Extracting python-3.12.7-hc5c86c4_0_cpython.conda
Extracting libcurl-8.10.1-hbbe4b11_0.conda
Extracting menuinst-2.2.0-py312h7900ff3_0.conda
Extracting archspec-0.2.3-pyhd8ed1ab_0.conda
Extracting boltons-24.0.0-pyhd8ed1ab_0.conda
Extracting brotli-python-1.1.0-py312h2ec8cdc_2.conda
Extracting certifi-2024.8.30-pyhd8ed1ab_0.conda
Extracting charset-normalizer-3.4.0-pyhd8ed1ab_0.conda
Extracting colorama-0.4.6-pyhd8ed1ab_0.tar.bz2
Extracting distro-1.9.0-pyhd8ed1ab_0.conda
Extracting frozendict-2.4.6-py312h66e93f0_0.conda
Extracting hpack-4.0.0-pyh9f0ad1d_0.tar.bz2
Extracting hyperframe-6.0.1-pyhd8ed1ab_0.tar.bz2
Extracting idna-3.10-pyhd8ed1ab_0.conda
Extracting jsonpointer-3.0.0-py312h7900ff3_1.conda
Extracting libmamba-1.5.9-h4cc3d14_0.conda
Extracting packaging-24.1-pyhd8ed1ab_0.conda
Extracting platformdirs-4.3.6-pyhd8ed1ab_0.conda
Extracting pluggy-1.5.0-pyhd8ed1ab_0.conda
Extracting pycosat-0.6.6-py312h98912ed_0.conda
Extracting pycparser-2.22-pyhd8ed1ab_0.conda
Extracting pysocks-1.7.1-pyha2e5f31_6.tar.bz2
Extracting ruamel.yaml.clib-0.2.8-py312h66e93f0_1.conda
Extracting setuptools-75.3.0-pyhd8ed1ab_0.conda
Extracting truststore-0.10.0-pyhd8ed1ab_0.conda
Extracting wheel-0.45.0-pyhd8ed1ab_0.conda
Extracting cffi-1.17.1-py312h06ac9bb_0.conda
Extracting h2-4.1.0-pyhd8ed1ab_0.tar.bz2
Extracting jsonpatch-1.33-pyhd8ed1ab_0.conda
Extracting libmambapy-1.5.9-py312h7fb9e8e_0.conda
Extracting pip-24.3.1-pyh8b19718_0.conda
Extracting ruamel.yaml-0.18.6-py312h66e93f0_1.conda
Extracting tqdm-4.67.0-pyhd8ed1ab_0.conda
Extracting zstandard-0.23.0-py312hef9b889_1.conda
Extracting conda-package-streaming-0.11.0-pyhd8ed1ab_0.conda
Extracting urllib3-2.2.3-pyhd8ed1ab_0.conda
Extracting conda-package-handling-2.4.0-pyh7900ff3_0.conda
Extracting requests-2.32.3-pyhd8ed1ab_0.conda
Extracting conda-24.9.2-py312h7900ff3_0.conda
Extracting conda-libmamba-solver-24.9.0-pyhd8ed1ab_0.conda
Extracting mamba-1.5.9-py312h9460a1c_0.conda
mkdir: cannot create directory ‘/home/mtankersley/.conda’: No such file or directory
[mtankersley@muskox mtankersley]$ 
```

</details>

### Installed packages

```shell
None
```

### Environment info

```shell
None
```

**Comment by mdtanker** [comment]
I think I have fixed the by setting the HOME environment variable to the same thing as the prefix during the install with:
```
(setenv HOME /local/data/muskox/Users/mtankersley/miniforge3 ; bash Miniforge3-Linux-x86_64.sh -p /local/data/muskox/Users/mtankersley/miniforge3)
```
When prompted to update my shell profile to automatically initialize conda I choose no. 

Running `conda init` give the following error:

```
[mtankersley@muskox mtankersley]$ conda init
[sudo] password for mtankersley: 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/cli/main.py", line 61, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 205, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/cli/main_init.py", line 162, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/core/initialize.py", line 139, in initialize
        run_plan_elevated(plan2)
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/core/initialize.py", line 852, in run_plan_elevated
        result = subprocess_call(
                 ^^^^^^^^^^^^^^^^
      File "/local/data/muskox/Users/mtankersley/miniforge3/lib/python3.12/site-packages/conda/gateways/subprocess.py", line 129, in subprocess_call
        raise CalledProcessError(rc, command, output=formatted_output)
    subprocess.CalledProcessError: Command '['sudo', '/local/data/muskox/Users/mtankersley/miniforge3/bin/python', '-m', 'conda.core.initialize']' returned non-zero exit status 1.

`$ /local/data/muskox/Users/mtankersley/miniforge3/bin/conda init`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/local/data/muskox/Users/mtankersley/miniforge3/bin/conda
         CONDA_PYTHON_EXE=/local/data/muskox/Users/mtankersley/miniforge3/bin/python
               CONDA_ROOT=/local/data/muskox/Users/mtankersley/miniforge3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/local/data/muskox/Users/mtankersley/miniforge3/condabin:/usr/local/bi
                          n:/usr/bin:/usr/local/sbin:/usr/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/mtankersley/.condarc
 populated config files : /local/data/muskox/Users/mtankersley/miniforge3/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.9.2=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /local/data/muskox/Users/mtankersley/miniforge3  (writable)
      conda av data dir : /local/data/muskox/Users/mtankersley/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /local/data/muskox/Users/mtankersley/miniforge3/pkgs
                          /home/mtankersley/.conda/pkgs
       envs directories : /local/data/muskox/Users/mtankersley/miniforge3/envs
                          /home/mtankersley/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Linux/3.10.0-1160.71.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.9
                UID:GID : 2844:2844
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n
```

It looks like the user config file is still pointing to my home directory, instead of the directory I chose to install into with --prefix: ` user config file : /home/mtankersley/.condarc`

**Comment by mdtanker** [comment]
I've solved this but wanted to add these instructions for anyone else having the same issue.

* SSH into your remote server
* cd to whatever directory you want miniforge installed in
    *  `cd example/directory`
* download the .sh script following instructions at https://github.com/conda-forge/miniforge
    * `wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-linux-x86_64.sh"`  
* temporarily set the HOME environment variable as the directory you are in
    * `export HOME="/example/directory"`
* run the installation
    * `bash Miniforge3-linux-x86_64.sh`
* accept license and say no to automatically initializing conda
* add miniforge to PATH
    * `export PATH="/example/directory/miniforge3/bin:$PATH"`
*  run `conda init` and `mamba init`, which will make a `.bashrc` in the current directory
* manually add the HOME variable set above to this `.bashrc` file
* run `source .bashrc`

Then every time you want to use mamba, cd into this directory and run `source .bashrc`.  This is currently working for me. These steps are necessary since I'm working on a server where I don't have a home directory and don't have write permission to the `.bashrc` file, but I have a user directory is a different location.
