### ISSUE TITLE
Installing from requirements file not working on Windows 11

### ISSUE THREAD

**Issue by mbarison** [conda-forge/miniforge#688]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Using conda 23.11.0 on Windows 11, I am trying to install packages from a requirements file. The packages get downloaded, but installation fails with a Python exception. Here's the error report:

```
Downloading and Extracting Packages:

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\cli\main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\cli\conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\notices\core.py", line 119, in wrapper
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\cli\main_install.py", line 140, in execute
        return install(args, parser, "install")
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\cli\install.py", line 438, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\cli\install.py", line 471, in handle_txn
        unlink_link_transaction.execute()
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\core\link.py", line 343, in execute
        self.verify()
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\common\io.py", line 85, in decorated
        return f(*args, **kwds)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\core\link.py", line 286, in verify
        self.prepare()
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\core\link.py", line 270, in prepare
        grps = self._prepare(
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\core\link.py", line 404, in _prepare
        packages_info_to_link = tuple(
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\core\link.py", line 405, in <genexpr>
        read_package_info(prec, pcrec)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\gateways\disk\read.py", line 115, in read_package_info
        paths_data = read_paths_json(epd)
      File "C:\ProgramData\miniforge3\lib\site-packages\conda\gateways\disk\read.py", line 189, in read_paths_json
        data = json.load(paths_json)
      File "C:\ProgramData\miniforge3\lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
      File "C:\ProgramData\miniforge3\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\ProgramData\miniforge3\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\ProgramData\miniforge3\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ C:\ProgramData\miniforge3\Scripts\conda-script.py install --file requirements.txt`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=C:\Users\barisma\Documents\canfed\.conda
                CONDA_EXE=C:\ProgramData\miniforge3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\miniforge3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\barisma\Documents\canfed\.conda
    CONDA_PROMPT_MODIFIER=(C:\Users\barisma\Documents\canfed\.conda)
         CONDA_PYTHON_EXE=C:\ProgramData\miniforge3\python.exe
               CONDA_ROOT=C:\ProgramData\miniforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\barisma
               LD_PRELOAD=<not set>
                     PATH=C:\Users\barisma\Documents\canfed\.conda;C:\Users\barisma\Documents\ca
                          nfed\.conda\Library\mingw-
                          w64\bin;C:\Users\barisma\Documents\canfed\.conda\Library\usr\bin;C:\Us
                          ers\barisma\Documents\canfed\.conda\Library\bin;C:\Users\barisma\Docum
                          ents\canfed\.conda\Scripts;C:\Users\barisma\Documents\canfed\.conda\bi
                          n;.;C:\Program Files\RStudio\resources\app\bin\quarto\bin;C:\Program
                          Files\Python310\Scripts;C:\Program Files\Python310;C:\Program Files
                          (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\S
                          ystem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\Sys
                          tem32\OpenSSH;C:\Program Files\dotnet;C:\Program
                          Files\PowerShell\7;C:\Program
                          Files\RStudio\resources\app\bin\quarto\bin;C:\Program
                          Files\RStudio\resources\app\bin\quarto\bin\tools;C:\Program
                          Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program
                          Files\Azure Data Studio\bin;C:\Users\barisma\AppData\Local\Microsoft\W
                          indowsApps;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files\R\
                          R-
                          4.2.3\bin;C:\rtools42\usr\bin;C:\Users\barisma\AppData\Roaming\Python\
                          Python310\Scripts;C:\ProgramData\miniforge3\condabin;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\barisma\Documents\canfed\.conda\Library\ssl\cacert.pem

     active environment : C:\Users\barisma\Documents\canfed\.conda
    active env location : C:\Users\barisma\Documents\canfed\.conda
            shell level : 1
       user config file : C:\Users\barisma\.condarc
 populated config files : C:\ProgramData\miniforge3\.condarc
                          C:\Users\barisma\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\ProgramData\miniforge3  (read only)
      conda av data dir : C:\ProgramData\miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : ***/artifactory/api/conda/conda-forge-remote/win-64
                          ***/artifactory/api/conda/conda-forge-remote/noarch
                          ***/artifactory/api/conda/conda-nvidia-remote/win-64
                          ***/artifactory/api/conda/conda-nvidia-remote/noarch
                          ***/artifactory/api/conda/conda-pytorch-remote/win-64
                          ***/artifactory/api/conda/conda-pytorch-remote/noarch
          package cache : C:\ProgramData\miniforge3\pkgs
                          C:\Users\barisma\.conda\pkgs
                          C:\Users\barisma\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\barisma\.conda\envs
                          C:\ProgramData\miniforge3\envs
                          C:\Users\barisma\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.32.3 CPython/3.10.13 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload did not complete.
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2466b09_7    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
ca-certificates           2024.8.30            h56e8100_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
libexpat                  2.6.4                he0c23c2_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
libffi                    3.4.2                h8ffe710_5    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
libsqlite                 3.47.0               h2466b09_1    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
libzlib                   1.3.1                h2466b09_2    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
openssl                   3.4.0                h2466b09_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
pip                       24.3.1             pyh8b19718_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
python                    3.11.10         hce54a09_3_cpython    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
setuptools                75.6.0             pyhff2d567_1    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
tk                        8.6.13               h5226925_1    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
tzdata                    2024b                hc8b5060_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
ucrt                      10.0.22621.0         h57928b3_1    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
vc                        14.3                ha32ba9b_23    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
vc14_runtime              14.42.34433         he29a5d6_23    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
vs2015_runtime            14.42.34433         hdffcdeb_23    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
wheel                     0.45.1             pyhd8ed1ab_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
xz                        5.2.6                h8d14728_0    https://artifactory.cloud.statcan.ca/artifactory/api/conda/conda-forge-remote
```

### Environment info

```shell
active environment : C:\Users\barisma\Documents\canfed\.conda
    active env location : C:\Users\barisma\Documents\canfed\.conda
            shell level : 1
       user config file : C:\Users\barisma\.condarc
 populated config files : C:\ProgramData\miniforge3\.condarc
                          C:\Users\barisma\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\ProgramData\miniforge3  (read only)
      conda av data dir : C:\ProgramData\miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : ***/artifactory/api/conda/conda-forge-remote/win-64
                          ***/artifactory/api/conda/conda-forge-remote/noarch
                          ***/artifactory/api/conda/conda-nvidia-remote/win-64
                          ***/artifactory/api/conda/conda-nvidia-remote/noarch
                          ***/artifactory/api/conda/conda-pytorch-remote/win-64
                          ***/artifactory/api/conda/conda-pytorch-remote/noarch
          package cache : C:\ProgramData\miniforge3\pkgs
                          C:\Users\barisma\.conda\pkgs
                          C:\Users\barisma\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\barisma\.conda\envs
                          C:\ProgramData\miniforge3\envs
                          C:\Users\barisma\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.32.3 CPython/3.10.13 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
I'm not sure but:

1. You have the combination of the following 3 channels in your settings: conda-forge, pytorch, nvidia
2. pytorch and nvidia REQUIRE the `main` channel.
3. pytorch has just deprecated their support for their conda-channel as a whole.


I'm going to guess that the environment you had created was with the channels: `main`, `pytorch` and `nvidia`. These have package names that are not compatible with conda-forge's.

I would suggest that you try to rebuild your environment piece by piece.

Without you sharing the environment.yml file that is as much help as we can provide.

**Comment by mbarison** [comment]
Hi,

we use artifactory at work to mirror the conda channels. I don't think channels are an issue, because the same configuration works on Windows 10 and Linux machines.

**Comment by hmaarrfk** [comment]
on windows for pytorch, you need to use

* conda + `nvidia` `pytorch` + `main`

or

* pip + `pypi`

As soon as you use the `main` channel, it is incompatible with `conda-forge`. Efforts for getting pytorch working through conda-forge on windows can be observed https://github.com/conda-forge/pytorch-cpu-feedstock/

If you need further help, you must provide us with minimum reporducible example of your requirements.txt file.

Trim it down until you see an error.

Then take it home, outside of your artifactory bubble, and try it again. see if the error persists. If it does, report back and let us know.

**Comment by mbarison** [comment]
Ok, but if a package is incompatible, I expect an error message and a graceful exit, not a **Python exception from the miniforge core**.

Does what I say make sense?

**Comment by mbarison** [comment]
Here is the requirements file:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
anyio=4.4.0=pyhd8ed1ab_0
argon2-cffi=23.1.0=pyhd8ed1ab_0
argon2-cffi-bindings=21.2.0=py312h4389bb4_5
arrow=1.3.0=pyhd8ed1ab_0
astroid=3.2.2=py312h2e8e312_0
asttokens=2.4.1=pyhd8ed1ab_0
async-lru=2.0.4=pyhd8ed1ab_0
attrs=23.2.0=pyh71513ae_0
aws-c-auth=0.7.22=ha1d026d_6
aws-c-cal=0.6.15=hea5f451_1
aws-c-common=0.9.23=h2466b09_0
aws-c-compression=0.2.18=hea5f451_7
aws-c-event-stream=0.4.2=ha301515_14
aws-c-http=0.8.2=hb4b72d7_3
aws-c-io=0.14.9=h5ec1eae_3
aws-c-mqtt=0.10.4=haec3ea0_7
aws-c-s3=0.5.10=h7545387_4
aws-c-sdkutils=0.1.16=hea5f451_3
aws-checksums=0.1.18=hea5f451_7
aws-crt-cpp=0.26.12=h90a6bef_1
aws-sdk-cpp=1.11.329=h31ee193_6
azure-core-cpp=1.12.0=haf5610f_0
azure-identity-cpp=1.8.0=h8578521_1
azure-storage-blobs-cpp=12.11.0=h39eb5e7_1
azure-storage-common-cpp=12.6.0=h8578521_1
babel=2.14.0=pyhd8ed1ab_0
beautifulsoup4=4.12.3=pyha770c72_0
black=24.4.2=py312h2e8e312_0
bleach=6.1.0=pyhd8ed1ab_0
blosc=1.21.6=h85f69ea_0
branca=0.7.2=pyhd8ed1ab_0
brotli=1.1.0=hcfcfb64_1
brotli-bin=1.1.0=hcfcfb64_1
brotli-python=1.1.0=py312h53d5487_1
#build=0.7.0=pyhd8ed1ab_0
bzip2=1.0.8=hcfcfb64_5
c-ares=1.28.1=hcfcfb64_0
ca-certificates=2024.8.30=h56e8100_0
cached-property=1.5.2=hd8ed1ab_1
cached_property=1.5.2=pyha770c72_1
cairo=1.18.0=h91e5215_2
certifi=2024.8.30=pyhd8ed1ab_0
cffi=1.16.0=py312he70551f_0
cfgv=3.3.1=pyhd8ed1ab_0
cfitsio=4.4.1=hc2ea260_0
charset-normalizer=3.3.2=pyhd8ed1ab_0
click=8.1.7=win_pyh7428d3b_0
click-plugins=1.1.1=py_0
cligj=0.7.2=pyhd8ed1ab_1
colorama=0.4.6=pyhd8ed1ab_0
comm=0.2.2=pyhd8ed1ab_0
contourpy=1.2.1=py312h0d7def4_0
cycler=0.12.1=pyhd8ed1ab_0
debugpy=1.8.2=py312h275cf98_0
decorator=5.1.1=pyhd8ed1ab_0
defusedxml=0.7.1=pyhd8ed1ab_0
dill=0.3.8=pyhd8ed1ab_0
distlib=0.3.8=pyhd8ed1ab_0
entrypoints=0.4=pyhd8ed1ab_0
et_xmlfile=1.1.0=pyhd8ed1ab_0
exceptiongroup=1.2.0=pyhd8ed1ab_2
executing=2.0.1=pyhd8ed1ab_0
expat=2.6.2=h63175ca_0
filelock=3.15.4=pyhd8ed1ab_0
fiona=1.9.6=py312h4a86439_3
fmt=10.2.1=h181d51b_0
folium=0.17.0=pyhd8ed1ab_0
font-ttf-dejavu-sans-mono=2.37=hab24e00_0
font-ttf-inconsolata=3.000=h77eed37_0
font-ttf-source-code-pro=2.038=h77eed37_0
font-ttf-ubuntu=0.83=h77eed37_2
fontconfig=2.14.2=hbde0cde_0
fonts-conda-ecosystem=1=0
fonts-conda-forge=1=0
fonttools=4.53.0=py312h4389bb4_0
fqdn=1.5.1=pyhd8ed1ab_0
freetype=2.12.1=hdaf720e_2
freexl=2.0.0=h8276f4a_0
gdal=3.9.1=py312h7090a6d_2
geopandas=1.0.1=pyhd8ed1ab_0
geopandas-base=1.0.1=pyha770c72_0
geos=3.12.1=h1537add_0
geotiff=1.7.3=hd7df778_1
h11=0.14.0=pyhd8ed1ab_0
h2=4.1.0=pyhd8ed1ab_0
hdf4=4.2.15=h5557f11_7
hdf5=1.14.3=nompi_h2b43c12_105
hpack=4.0.0=pyh9f0ad1d_0
httpcore=1.0.5=pyhd8ed1ab_0
httpx=0.27.2=pyhd8ed1ab_0
hyperframe=6.0.1=pyhd8ed1ab_0
icu=73.2=h63175ca_0
identify=2.5.36=pyhd8ed1ab_0
idna=3.7=pyhd8ed1ab_0
importlib-metadata=8.0.0=pyha770c72_0
importlib_metadata=8.0.0=hd8ed1ab_0
importlib_resources=6.4.5=pyhd8ed1ab_0
intel-openmp=2023.2.0=h57928b3_50497
ipykernel=6.29.5=pyh4bbf305_0
ipython=8.26.0=pyh7428d3b_0
ipywidgets=8.1.5=pyhd8ed1ab_0
isoduration=20.11.0=pyhd8ed1ab_0
isort=5.13.2=pyhd8ed1ab_0
jedi=0.19.1=pyhd8ed1ab_0
jellyfish=1.0.4=py312h2615798_0
jinja2=3.1.4=pyhd8ed1ab_0
joblib=1.4.2=pyhd8ed1ab_0
json5=0.9.25=pyhd8ed1ab_0
jsonpointer=3.0.0=py312h2e8e312_1
jsonschema=4.23.0=pyhd8ed1ab_0
jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
jupyter=1.1.1=pyhd8ed1ab_0
jupyter-lsp=2.2.5=pyhd8ed1ab_0
jupyter_client=8.6.2=pyhd8ed1ab_0
jupyter_console=6.6.3=pyhd8ed1ab_0
jupyter_core=5.7.2=py312h2e8e312_0
jupyter_events=0.10.0=pyhd8ed1ab_0
jupyter_server=2.14.2=pyhd8ed1ab_0
jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
jupyterlab=4.2.5=pyhd8ed1ab_0
jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
jupyterlab_server=2.27.3=pyhd8ed1ab_0
jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
#kamori=24.10.3=pypi_0
kealib=1.5.3=h6c43f9b_1
kiwisolver=1.4.5=py312h0d7def4_1
krb5=1.21.3=hdf4eb48_0
lcms2=2.16=h67d730c_0
lerc=4.0.0=h63175ca_0
libabseil=20240116.2=cxx17_h63175ca_0
libaec=1.1.3=h63175ca_0
libarchive=3.7.4=haf234dc_0
libarrow=16.1.0=h4b09723_11_cpu
libarrow-acero=16.1.0=he0c23c2_11_cpu
libarrow-dataset=16.1.0=he0c23c2_11_cpu
libarrow-substrait=16.1.0=h1f0e801_11_cpu
libblas=3.9.0=20_win64_mkl
libboost-headers=1.85.0=h57928b3_2
libbrotlicommon=1.1.0=hcfcfb64_1
libbrotlidec=1.1.0=hcfcfb64_1
libbrotlienc=1.1.0=hcfcfb64_1
libcblas=3.9.0=20_win64_mkl
libcrc32c=1.1.2=h0e60522_0
libcurl=8.8.0=hd5e4a3a_1
libdeflate=1.20=hcfcfb64_0
libevent=2.1.12=h3671451_1
libexpat=2.6.2=h63175ca_0
libffi=3.4.2=h8ffe710_5
libgdal=3.9.1=h954eb94_2
libglib=2.80.2=h7025463_1
libgoogle-cloud=2.26.0=h5e7cea3_0
libgoogle-cloud-storage=2.26.0=he5eb982_0
libgrpc=1.62.2=h5273850_0
libhwloc=2.11.0=default_h8125262_1000
libiconv=1.17=hcfcfb64_2
libintl=0.22.5=h5728263_2
libjpeg-turbo=3.0.0=hcfcfb64_1
libkml=1.3.0=haf3e7a6_1018
liblapack=3.9.0=20_win64_mkl
libnetcdf=4.9.2=nompi_h92078aa_114
libparquet=16.1.0=h178134c_11_cpu
libpng=1.6.43=h19919ed_0
libpq=16.3=hab9416b_0
libprotobuf=4.25.3=h503648d_0
libre2-11=2023.09.01=hf8d8778_2
librttopo=1.1.0=h94c4f80_15
libsodium=1.0.18=h8d14728_1
libspatialite=5.1.0=h1b797e6_7
libsqlite=3.46.0=h2466b09_0
libssh2=1.11.0=h7dfc565_0
libthrift=0.19.0=ha2b3283_1
libtiff=4.6.0=hddb2be6_3
libutf8proc=2.8.0=h82a8f57_0
libwebp-base=1.4.0=hcfcfb64_0
libxcb=1.16=hcd874cb_0
libxml2=2.12.7=h283a6d9_1
libzip=1.10.1=h1d365fa_3
libzlib=1.3.1=h2466b09_1
lz4-c=1.9.4=hcfcfb64_0
lzo=2.10=hcfcfb64_1001
m2w64-gcc-libgfortran=5.3.0=6
m2w64-gcc-libs=5.3.0=7
m2w64-gcc-libs-core=5.3.0=7
m2w64-gmp=6.1.0=2
m2w64-libwinpthread-git=5.0.0.4634.697f757=2
mapclassify=2.6.1=pyhd8ed1ab_0
markupsafe=2.1.5=py312he70551f_0
matplotlib-base=3.8.4=py312hfee7060_2
matplotlib-inline=0.1.7=pyhd8ed1ab_0
mccabe=0.7.0=pyhd8ed1ab_0
minizip=4.0.6=hb638d1e_0
mistune=3.0.2=pyhd8ed1ab_0
mkl=2023.2.0=h6a75c08_50497
msys2-conda-epoch=20160418=1
munkres=1.1.4=pyh9f0ad1d_0
mypy_extensions=1.0.0=pyha770c72_0
nbclient=0.10.0=pyhd8ed1ab_0
nbconvert-core=7.16.4=pyhd8ed1ab_1
nbformat=5.10.4=pyhd8ed1ab_0
nest-asyncio=1.6.0=pyhd8ed1ab_0
networkx=3.3=pyhd8ed1ab_1
nodeenv=1.9.1=pyhd8ed1ab_0
notebook=7.2.2=pyhd8ed1ab_0
notebook-shim=0.2.4=pyhd8ed1ab_0
numexpr=2.10.0=mkl_py312h295738f_0
numpy=2.1.1=py312h49bc9c5_0
openjdk=22.0.1=h57928b3_1
openjpeg=2.5.2=h3d672ee_0
openpyxl=3.1.4=py312he70551f_0
openssl=3.3.2=h2466b09_0
orc=2.0.1=h7e885a9_1
overrides=7.7.0=pyhd8ed1ab_0
packaging=24.1=pyhd8ed1ab_0
pandas=2.2.2=py312h72972c8_1
pandocfilters=1.5.0=pyhd8ed1ab_0
parso=0.8.4=pyhd8ed1ab_0
pathspec=0.12.1=pyhd8ed1ab_0
pcre2=10.44=h3d7b363_0
pep517=0.13.0=pyhd8ed1ab_0
pickleshare=0.7.5=py_1003
pillow=10.4.0=py312h381445a_0
pip=24.0=pyhd8ed1ab_0
pixman=0.43.4=h63175ca_0
pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
platformdirs=4.2.2=pyhd8ed1ab_0
poppler=24.04.0=h747fd5a_0
poppler-data=0.4.12=hd8ed1ab_0
postgresql=16.3=h7f155c9_0
pre-commit=3.7.1=pyha770c72_0
proj=9.4.1=hd9569ee_0
prometheus_client=0.20.0=pyhd8ed1ab_0
prompt-toolkit=3.0.47=pyha770c72_0
prompt_toolkit=3.0.47=hd8ed1ab_0
psutil=6.0.0=py312h4389bb4_0
pthread-stubs=0.4=hcd874cb_1001
pthreads-win32=2.9.1=hfa6e2cd_3
pure_eval=0.2.2=pyhd8ed1ab_0
pyarrow=16.1.0=py312h7e22eef_4
pyarrow-core=16.1.0=py312h3529c54_4_cpu
pycparser=2.22=pyhd8ed1ab_0
pygments=2.18.0=pyhd8ed1ab_0
pylint=3.2.5=pyhd8ed1ab_0
pyogrio=0.9.0=py312hd215820_0
pyparsing=3.1.2=pyhd8ed1ab_0
pyproj=3.6.1=py312h6f27134_7
pysocks=1.7.1=pyh0701188_6
python=3.12.4=h889d299_0_cpython
python-dateutil=2.9.0=pyhd8ed1ab_0
python-fastjsonschema=2.20.0=pyhd8ed1ab_0
python-json-logger=2.0.7=pyhd8ed1ab_0
python-tzdata=2024.1=pyhd8ed1ab_0
python_abi=3.12=4_cp312
pytz=2024.1=pyhd8ed1ab_0
pywin32=306=py312h53d5487_2
pywinpty=2.0.13=py312h275cf98_1
pyyaml=6.0.1=py312he70551f_1
pyzmq=26.0.3=py312hd7027bb_0
re2=2023.09.01=hd3b24a8_2
recordlinkage=0.16=pyhd8ed1ab_0
referencing=0.35.1=pyhd8ed1ab_0
requests=2.32.3=pyhd8ed1ab_0
rfc3339-validator=0.1.4=pyhd8ed1ab_0
rfc3986-validator=0.1.1=pyh9f0ad1d_0
rpds-py=0.20.0=py312h2615798_1
scikit-learn=1.5.1=py312h816cc57_0
scipy=1.14.0=py312h1f4e10d_0
send2trash=1.8.3=pyh5737063_0
setuptools=70.1.1=pyhd8ed1ab_0
setuptools-scm=8.1.0=pyhd8ed1ab_0
setuptools_scm=8.1.0=hd8ed1ab_0
shapely=2.0.4=py312h91267bd_1
six=1.16.0=pyh6c4a22f_0
snappy=1.2.1=h23299a8_0
sniffio=1.3.1=pyhd8ed1ab_0
soupsieve=2.5=pyhd8ed1ab_1
spdlog=1.13.0=h64d2f7d_0
sqlite=3.46.0=h2466b09_0
stack_data=0.6.2=pyhd8ed1ab_0
symlink-exe-runtime=1.0=hcfcfb64_0
tabula-py=2.7.0=py312h2e8e312_1
tbb=2021.12.0=hc790b64_2
terminado=0.18.1=pyh5737063_0
threadpoolctl=3.5.0=pyhc1e730c_0
tiledb=2.24.1=hb5d6afa_2
tinycss2=1.3.0=pyhd8ed1ab_0
tk=8.6.13=h5226925_1
tomli=2.0.1=pyhd8ed1ab_0
tomlkit=0.12.5=pyha770c72_0
tornado=6.4.1=py312h4389bb4_0
traitlets=5.14.3=pyhd8ed1ab_0
types-python-dateutil=2.9.0.20240906=pyhd8ed1ab_0
typing-extensions=4.12.2=hd8ed1ab_0
typing_extensions=4.12.2=pyha770c72_0
typing_utils=0.1.0=pyhd8ed1ab_0
tzdata=2024a=h0c530f3_0
ucrt=10.0.22621.0=h57928b3_0
ukkonen=1.0.1=py312h0d7def4_4
uri-template=1.3.0=pyhd8ed1ab_0
uriparser=0.9.8=h5a68840_0
urllib3=2.2.2=pyhd8ed1ab_1
vc=14.3=h8a93ad2_20
vc14_runtime=14.40.33810=ha82c5b3_20
virtualenv=20.26.3=pyhd8ed1ab_0
vs2015_runtime=14.40.33810=h3bf8584_20
wcwidth=0.2.13=pyhd8ed1ab_0
webcolors=24.8.0=pyhd8ed1ab_0
webencodings=0.5.1=pyhd8ed1ab_2
websocket-client=1.8.0=pyhd8ed1ab_0
wheel=0.43.0=pyhd8ed1ab_1
widgetsnbextension=4.0.13=pyhd8ed1ab_0
win_inet_pton=1.1.0=pyhd8ed1ab_6
winpty=0.4.3=4
xerces-c=3.2.5=h63175ca_0
xorg-libxau=1.0.11=hcd874cb_0
xorg-libxdmcp=1.1.3=hcd874cb_0
xyzservices=2024.6.0=pyhd8ed1ab_0
xz=5.2.6=h8d14728_0
yaml=0.2.5=h8ffe710_2
zeromq=4.3.5=he1f189c_4
zipp=3.19.2=pyhd8ed1ab_0
zlib=1.3.1=h2466b09_1
zstandard=0.22.0=py312h7606c53_1
zstd=1.5.6=h0ea2cb4_0
```

**Comment by hmaarrfk** [comment]
> Ok, but if a package is incompatible, I expect an error message and a graceful exit, not a Python exception from the miniforge core.

yes it does, but that was not stated in your original issue.


I notice that you are using `conda 23.11.0` as stated in your original message. Are you able to update to 24.X x=something? Some of these usability things have been improving over time.

**Comment by mbarison** [comment]
Unfortunately not, I am relying on the IT department doing our updates, I was looking for a quick fix. Thanks.

**Comment by hmaarrfk** [comment]
ok. please work with your IT team then.

Please note that miniforge is meant to be installed as a user, not a shared installation.
