### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found

### ISSUE THREAD

**Issue by aloboa** [conda-forge/miniforge#698]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

In previously working system (Ubuntu `22.04.5),` as soon as I enter mamba, I get today:
```
(base) alobo2@alobo-ws:~$ mamba
Traceback (most recent call last):
  File "/home/alobo2/miniforge3/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/alobo2/miniforge3/lib/python3.12/site-packages/mamba/mamba.py", line 45, in <module>
    import libmambapy as api
  File "/home/alobo2/miniforge3/lib/python3.12/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/alobo2/miniforge3/lib/python3.12/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/alobo2/miniforge3/lib/python3.12/site-packages/libmambapy/../../.././libcurl.so.4)
```

```
(base) alobo2@alobo-ws:~$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

(base) alobo2@alobo-ws:/lib/x86_64-linux-gnu$ ls -l libssl*
-rw-r--r-- 1 root root  434928 abr 11  2024 libssl3.so
-rw-r--r-- 1 root root 1231818 ago 20 19:27 libssl.a
lrwxrwxrwx 1 root root      11 ago 20 19:27 libssl.so -> libssl.so.3
-rw-r--r-- 1 root root  667864 ago 20 19:27 libssl.so.3
```

### Installed packages

```shell
(base) alobo2@alobo-ws:~$ conda list
Error while loading conda entry point: conda-libmamba-solver (/lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/alobo2/miniforge3/lib/python3.12/site-packages/libmambapy/../../.././libcurl.so.4))
# packages in environment at /home/alobo2/miniforge3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.32.3               h4bc722e_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     24.7.1          py312h7900ff3_0    conda-forge
conda-libmamba-solver     24.7.0                   pypi_0    pypi
conda-package-handling    2.3.0                    pypi_0    pypi
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
fmt                       10.2.1               h00ab1b0_0    conda-forge
frozendict                2.4.4           py312h66e93f0_1    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.10                     pypi_0    pypi
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py312h7900ff3_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libmamba                  1.5.8                had39da4_0    conda-forge
libmambapy                1.5.9           py312h7fb9e8e_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsolv                   0.7.28               hfc55251_2    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.6               h232c23b_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     1.5.9                    pypi_0    pypi
menuinst                  2.1.2           py312h7900ff3_1    conda-forge
ncurses                   6.4.20240210         h59595ed_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pip                       24.2                     pypi_0    pypi
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6                    pypi_0    pypi
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.6          hc5c86c4_1_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.32.3                   pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
ruamel.yaml               0.18.6          py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.8           py310h2372a71_0    conda-forge
setuptools                74.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
truststore                0.9.2                    pypi_0    pypi
tzdata                    2024a                h8827d51_1    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
(base) alobo2@alobo-ws:~$ conda info
Error while loading conda entry point: conda-libmamba-solver (/lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/alobo2/miniforge3/lib/python3.12/site-packages/libmambapy/../../.././libcurl.so.4))

     active environment : base
    active env location : /home/alobo2/miniforge3
            shell level : 1
       user config file : /home/alobo2/.condarc
 populated config files : /home/alobo2/miniforge3/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.7.1=0
                          __cuda=12.4=0
                          __glibc=2.35=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /home/alobo2/miniforge3  (writable)
      conda av data dir : /home/alobo2/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/alobo2/miniforge3/pkgs
                          /home/alobo2/.conda/pkgs
       envs directories : /home/alobo2/miniforge3/envs
                          /home/alobo2/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.6 Linux/6.8.0-40-generic ubuntu/22.04.5 glibc/2.35 solver/libmamba
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
What is the output of


env

**Comment by aloboa** [comment]
```
(base) alobo2@alobo-ws:~$ env
SHELL=/bin/bash
SESSION_MANAGER=local/alobo-ws:@/tmp/.ICE-unix/3561,unix/alobo-ws:/tmp/.ICE-unix/3561
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
SSH_AGENT_LAUNCHER=gnome-keyring
XDG_MENU_PREFIX=gnome-
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GTK_IM_MODULE=ibus
CONDA_EXE=/home/alobo2/miniforge3/bin/conda
_CE_M=
LANGUAGE=en_US:en
LC_ADDRESS=es_ES.UTF-8
GNOME_SHELL_SESSION_MODE=ubuntu
LC_NAME=es_ES.UTF-8
SSH_AUTH_SOCK=/run/user/1001/keyring/ssh
XMODIFIERS=@im=ibus
DESKTOP_SESSION=ubuntu
LC_MONETARY=es_ES.UTF-8
XML_CATALOG_FILES=file:///home/alobo2/miniforge3/etc/xml/catalog file:///etc/xml/catalog
GTK_MODULES=gail:atk-bridge
PWD=/home/alobo2
LOGNAME=alobo2
XDG_SESSION_DESKTOP=ubuntu
XDG_SESSION_TYPE=x11
CONDA_PREFIX=/home/alobo2/miniforge3
GPG_AGENT_INFO=/run/user/1001/gnupg/S.gpg-agent:0:1
SYSTEMD_EXEC_PID=3585
XAUTHORITY=/run/user/1001/gdm/Xauthority
WINDOWPATH=2
HOME=/home/alobo2
USERNAME=alobo2
IM_CONFIG_PHASE=1
LC_PAPER=es_ES.UTF-8
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=ubuntu:GNOME
VTE_VERSION=6800
CONDA_PROMPT_MODIFIER=(base) 
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/b5fff67e_3fce_4e08_b1ff_e797d61c7362
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LC_IDENTIFICATION=es_ES.UTF-8
_CE_CONDA=
LESSOPEN=| /usr/bin/lesspipe %s
USER=alobo2
GNOME_TERMINAL_SERVICE=:1.95
CONDA_SHLVL=1
DISPLAY=:1
SHLVL=1
LC_TELEPHONE=es_ES.UTF-8
QT_IM_MODULE=ibus
LC_MEASUREMENT=es_ES.UTF-8
CONDA_PYTHON_EXE=/home/alobo2/miniforge3/bin/python
XDG_RUNTIME_DIR=/run/user/1001
CONDA_DEFAULT_ENV=base
LC_TIME=es_ES.UTF-8
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
PATH=/home/alobo2/miniforge3/bin:/home/alobo2/miniforge3/condabin:/home/alobo2/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
GDMSESSION=ubuntu
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
LC_NUMERIC=es_ES.UTF-8
_=/usr/bin/env

```

**Comment by hmaarrfk** [comment]
did you add something in your `.bashrc` or your `.bash_profile` file that could be conflicting? did you try for example to install miniforge while anaconda was already installed?

**Comment by aloboa** [comment]
No, I just installed miniforge, my mamba comes from there. And regarding .bashrc, it is very old
```
(base) alobo@pop-os:~$ ls -l .bashrc
-rw-r--r-- 1 alobo alobo 4309 ene 19  2022 .bashrc
(base) alobo@pop-os:~$ ls -l .bash_profile
ls: cannot access '.bash_profile': No such file or directory
```

I really cannot figure out any reason for this error, I have been using mamba since October.

**Comment by hmaarrfk** [comment]
I don't really understand why your `conda-libmamba-solver` is installed from `pypy_0`. Did you type `pip install conda` somewhere?

On my machine:
```
$ conda list | grep -E "^conda"
conda                     24.11.0         py312h7900ff3_0    conda-forge
conda-build               24.5.1          py312h7900ff3_0    conda-forge
conda-forge-pinning       2024.12.16.17.14.48      hd8ed1ab_0    conda-forge
conda-index               0.5.0              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     24.7.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.4.0              pyha770c72_1    conda-forge
conda-package-streaming   0.11.0             pyhd8ed1ab_0    conda-forge
conda-smithy              3.45.0          unix_pyhd81877a_0    conda-forge
```

**Comment by aloboa** [comment]
This is what I have:

```
(base) alobo2@alobo-ws:~$ conda list | grep -E "^conda"
Error while loading conda entry point: conda-libmamba-solver (/lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /home/alobo2/miniforge3/lib/python3.12/site-packages/libmambapy/../../.././libcurl.so.4))
conda                     24.7.1          py312h7900ff3_0    conda-forge
conda-libmamba-solver     24.7.0                   pypi_0    pypi
conda-package-handling    2.3.0                    pypi_0    pypi
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
```


Actually my .bashrc is newer than the mamba installation, although I did not edit it directly myself. Perhaps some installation script modified it?
This is it:

```
(base) alobo2@alobo-ws:~$ more .bashrc
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
(base) alobo2@alobo-ws:~$ cat .bashrc
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/alobo2/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/alobo2/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/home/alobo2/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/home/alobo2/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/alobo2/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/home/alobo2/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<
```

**Comment by hmaarrfk** [comment]
I'm unfortunately out of ideas.

I would suggest:

1. Compressing your existing miniforge3 as a backup.
2. Reinstalling with  https://github.com/conda-forge/miniforge/releases/tag/24.11.2-1

**Comment by jjerphan** [comment]
It seems `libssl` is improperly dynamically linked with `libmambapy` (conda-forge's distribution must be used but your system's get picked instead).

Can you report the result of:

```
ldd /home/jjerphan/.local/miniforge3/envs/dev/lib/python3.12/site-packages/libmambapy/bindings.cpython-312-x86_64-linux-gnu.so
```

?

**Comment by aloboa** [comment]
I appreciate your help.
Unfortunately, I had to follow the advice by [hmaarrfk](https://github.com/hmaarrfk) and reinstall miniforge. I could copy back all the contents of my envs folder, and things work fine now. I'm sorry I did not report back here.
I also regret not having been able to clarify this issue.

**Comment by jjerphan** [comment]
No problem, it's fine.
